FROM polarismesh/polaris-server:v1.5.0

LABEL MAINTAINER = huyuanxin
LABEL EMAIL = huyuanxin1999@outlook.com

COPY ./config/polaris-server.yaml /root/

EXPOSE 8091 8090

CMD ["/root/polaris-server", "start"]


