version: "3"
services:
  polaris_server:
    image: polarismesh/polaris-server-standalone:latest
    container_name: polaris-server
    networks:
      - local
    ports:
      - "8090:8090"
      - "8091:8091"
      - "8093:8093"
      - "8761:8761"
      - "15010:15010"

  polaris_console:
    image: polarismesh/polaris-console:latest
    container_name: polaris-console
    networks:
      - local
    ports:
      - "8080:8080"
    volumes:
      - ./polaris-console.yaml:/root/polaris-console.yaml:ro
    depends_on:
      - polaris_server

networks:
  local:
    external: false
