// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthAction int32

const (
	AuthAction_ONLY_READ  AuthAction = 0
	AuthAction_READ_WRITE AuthAction = 1
)

var AuthAction_name = map[int32]string{
	0: "ONLY_READ",
	1: "READ_WRITE",
}
var AuthAction_value = map[string]int32{
	"ONLY_READ":  0,
	"READ_WRITE": 1,
}

func (x AuthAction) String() string {
	return proto.EnumName(AuthAction_name, int32(x))
}
func (AuthAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_auth_7f6a95f507eac77c, []int{0}
}

type ResourceType int32

const (
	ResourceType_Namespaces   ResourceType = 0
	ResourceType_Services     ResourceType = 1
	ResourceType_ConfigGroups ResourceType = 2
)

var ResourceType_name = map[int32]string{
	0: "Namespaces",
	1: "Services",
	2: "ConfigGroups",
}
var ResourceType_value = map[string]int32{
	"Namespaces":   0,
	"Services":     1,
	"ConfigGroups": 2,
}

func (x ResourceType) String() string {
	return proto.EnumName(ResourceType_name, int32(x))
}
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_auth_7f6a95f507eac77c, []int{1}
}

type LoginRequest struct {
	Owner                *wrappers.StringValue `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password             *wrappers.StringValue `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_7f6a95f507eac77c, []int{0}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetOwner() *wrappers.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *LoginRequest) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *LoginRequest) GetPassword() *wrappers.StringValue {
	if m != nil {
		return m.Password
	}
	return nil
}

type LoginResponse struct {
	UserId               *wrappers.StringValue `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role                 *wrappers.StringValue `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	OwnerId              *wrappers.StringValue `protobuf:"bytes,4,opt,name=owner_id,proto3" json:"owner_id,omitempty"`
	Token                *wrappers.StringValue `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_7f6a95f507eac77c, []int{1}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetUserId() *wrappers.StringValue {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *LoginResponse) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *LoginResponse) GetRole() *wrappers.StringValue {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *LoginResponse) GetOwnerId() *wrappers.StringValue {
	if m != nil {
		return m.OwnerId
	}
	return nil
}

func (m *LoginResponse) GetToken() *wrappers.StringValue {
	if m != nil {
		return m.Token
	}
	return nil
}

type User struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password             *wrappers.StringValue `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Owner                *wrappers.StringValue `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Source               *wrappers.StringValue `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	AuthToken            *wrappers.StringValue `protobuf:"bytes,6,opt,name=auth_token,proto3" json:"auth_token,omitempty"`
	TokenEnable          *wrappers.BoolValue   `protobuf:"bytes,7,opt,name=token_enable,proto3" json:"token_enable,omitempty"`
	Comment              *wrappers.StringValue `protobuf:"bytes,8,opt,name=comment,proto3" json:"comment,omitempty"`
	Ctime                *wrappers.StringValue `protobuf:"bytes,9,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Mtime                *wrappers.StringValue `protobuf:"bytes,10,opt,name=mtime,proto3" json:"mtime,omitempty"`
	UserType             *wrappers.StringValue `protobuf:"bytes,11,opt,name=user_type,proto3" json:"user_type,omitempty"`
	Mobile               *wrappers.StringValue `protobuf:"bytes,12,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email                *wrappers.StringValue `protobuf:"bytes,13,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_7f6a95f507eac77c, []int{2}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *User) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *User) GetPassword() *wrappers.StringValue {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *User) GetOwner() *wrappers.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *User) GetSource() *wrappers.StringValue {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *User) GetAuthToken() *wrappers.StringValue {
	if m != nil {
		return m.AuthToken
	}
	return nil
}

func (m *User) GetTokenEnable() *wrappers.BoolValue {
	if m != nil {
		return m.TokenEnable
	}
	return nil
}

func (m *User) GetComment() *wrappers.StringValue {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *User) GetCtime() *wrappers.StringValue {
	if m != nil {
		return m.Ctime
	}
	return nil
}

func (m *User) GetMtime() *wrappers.StringValue {
	if m != nil {
		return m.Mtime
	}
	return nil
}

func (m *User) GetUserType() *wrappers.StringValue {
	if m != nil {
		return m.UserType
	}
	return nil
}

func (m *User) GetMobile() *wrappers.StringValue {
	if m != nil {
		return m.Mobile
	}
	return nil
}

func (m *User) GetEmail() *wrappers.StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

type ModifyUserPassword struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OldPassword          *wrappers.StringValue `protobuf:"bytes,2,opt,name=old_password,proto3" json:"old_password,omitempty"`
	NewPassword          *wrappers.StringValue `protobuf:"bytes,3,opt,name=new_password,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ModifyUserPassword) Reset()         { *m = ModifyUserPassword{} }
func (m *ModifyUserPassword) String() string { return proto.CompactTextString(m) }
func (*ModifyUserPassword) ProtoMessage()    {}
func (*ModifyUserPassword) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_7f6a95f507eac77c, []int{3}
}
func (m *ModifyUserPassword) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyUserPassword.Unmarshal(m, b)
}
func (m *ModifyUserPassword) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyUserPassword.Marshal(b, m, deterministic)
}
func (dst *ModifyUserPassword) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyUserPassword.Merge(dst, src)
}
func (m *ModifyUserPassword) XXX_Size() int {
	return xxx_messageInfo_ModifyUserPassword.Size(m)
}
func (m *ModifyUserPassword) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyUserPassword.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyUserPassword proto.InternalMessageInfo

func (m *ModifyUserPassword) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ModifyUserPassword) GetOldPassword() *wrappers.StringValue {
	if m != nil {
		return m.OldPassword
	}
	return nil
}

func (m *ModifyUserPassword) GetNewPassword() *wrappers.StringValue {
	if m != nil {
		return m.NewPassword
	}
	return nil
}

type UserGroupRelation struct {
	GroupId              *wrappers.StringValue `protobuf:"bytes,1,opt,name=group_id,proto3" json:"group_id,omitempty"`
	Users                []*User               `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UserGroupRelation) Reset()         { *m = UserGroupRelation{} }
func (m *UserGroupRelation) String() string { return proto.CompactTextString(m) }
func (*UserGroupRelation) ProtoMessage()    {}
func (*UserGroupRelation) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_7f6a95f507eac77c, []int{4}
}
func (m *UserGroupRelation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGroupRelation.Unmarshal(m, b)
}
func (m *UserGroupRelation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGroupRelation.Marshal(b, m, deterministic)
}
func (dst *UserGroupRelation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGroupRelation.Merge(dst, src)
}
func (m *UserGroupRelation) XXX_Size() int {
	return xxx_messageInfo_UserGroupRelation.Size(m)
}
func (m *UserGroupRelation) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGroupRelation.DiscardUnknown(m)
}

var xxx_messageInfo_UserGroupRelation proto.InternalMessageInfo

func (m *UserGroupRelation) GetGroupId() *wrappers.StringValue {
	if m != nil {
		return m.GroupId
	}
	return nil
}

func (m *UserGroupRelation) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserGroup struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Owner                *wrappers.StringValue `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	AuthToken            *wrappers.StringValue `protobuf:"bytes,4,opt,name=auth_token,proto3" json:"auth_token,omitempty"`
	TokenEnable          *wrappers.BoolValue   `protobuf:"bytes,5,opt,name=token_enable,proto3" json:"token_enable,omitempty"`
	Comment              *wrappers.StringValue `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	Ctime                *wrappers.StringValue `protobuf:"bytes,7,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Mtime                *wrappers.StringValue `protobuf:"bytes,8,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Relation             *UserGroupRelation    `protobuf:"bytes,9,opt,name=relation,proto3" json:"relation,omitempty"`
	UserCount            *wrappers.UInt32Value `protobuf:"bytes,10,opt,name=user_count,proto3" json:"user_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UserGroup) Reset()         { *m = UserGroup{} }
func (m *UserGroup) String() string { return proto.CompactTextString(m) }
func (*UserGroup) ProtoMessage()    {}
func (*UserGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_7f6a95f507eac77c, []int{5}
}
func (m *UserGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGroup.Unmarshal(m, b)
}
func (m *UserGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGroup.Marshal(b, m, deterministic)
}
func (dst *UserGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGroup.Merge(dst, src)
}
func (m *UserGroup) XXX_Size() int {
	return xxx_messageInfo_UserGroup.Size(m)
}
func (m *UserGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGroup.DiscardUnknown(m)
}

var xxx_messageInfo_UserGroup proto.InternalMessageInfo

func (m *UserGroup) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *UserGroup) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *UserGroup) GetOwner() *wrappers.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *UserGroup) GetAuthToken() *wrappers.StringValue {
	if m != nil {
		return m.AuthToken
	}
	return nil
}

func (m *UserGroup) GetTokenEnable() *wrappers.BoolValue {
	if m != nil {
		return m.TokenEnable
	}
	return nil
}

func (m *UserGroup) GetComment() *wrappers.StringValue {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *UserGroup) GetCtime() *wrappers.StringValue {
	if m != nil {
		return m.Ctime
	}
	return nil
}

func (m *UserGroup) GetMtime() *wrappers.StringValue {
	if m != nil {
		return m.Mtime
	}
	return nil
}

func (m *UserGroup) GetRelation() *UserGroupRelation {
	if m != nil {
		return m.Relation
	}
	return nil
}

func (m *UserGroup) GetUserCount() *wrappers.UInt32Value {
	if m != nil {
		return m.UserCount
	}
	return nil
}

type ModifyUserGroup struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner                *wrappers.StringValue `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AuthToken            *wrappers.StringValue `protobuf:"bytes,4,opt,name=auth_token,proto3" json:"auth_token,omitempty"`
	TokenEnable          *wrappers.BoolValue   `protobuf:"bytes,5,opt,name=token_enable,proto3" json:"token_enable,omitempty"`
	Comment              *wrappers.StringValue `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	AddRelations         *UserGroupRelation    `protobuf:"bytes,7,opt,name=add_relations,proto3" json:"add_relations,omitempty"`
	RemoveRelations      *UserGroupRelation    `protobuf:"bytes,8,opt,name=remove_relations,proto3" json:"remove_relations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ModifyUserGroup) Reset()         { *m = ModifyUserGroup{} }
func (m *ModifyUserGroup) String() string { return proto.CompactTextString(m) }
func (*ModifyUserGroup) ProtoMessage()    {}
func (*ModifyUserGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_7f6a95f507eac77c, []int{6}
}
func (m *ModifyUserGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyUserGroup.Unmarshal(m, b)
}
func (m *ModifyUserGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyUserGroup.Marshal(b, m, deterministic)
}
func (dst *ModifyUserGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyUserGroup.Merge(dst, src)
}
func (m *ModifyUserGroup) XXX_Size() int {
	return xxx_messageInfo_ModifyUserGroup.Size(m)
}
func (m *ModifyUserGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyUserGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyUserGroup proto.InternalMessageInfo

func (m *ModifyUserGroup) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ModifyUserGroup) GetOwner() *wrappers.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *ModifyUserGroup) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ModifyUserGroup) GetAuthToken() *wrappers.StringValue {
	if m != nil {
		return m.AuthToken
	}
	return nil
}

func (m *ModifyUserGroup) GetTokenEnable() *wrappers.BoolValue {
	if m != nil {
		return m.TokenEnable
	}
	return nil
}

func (m *ModifyUserGroup) GetComment() *wrappers.StringValue {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *ModifyUserGroup) GetAddRelations() *UserGroupRelation {
	if m != nil {
		return m.AddRelations
	}
	return nil
}

func (m *ModifyUserGroup) GetRemoveRelations() *UserGroupRelation {
	if m != nil {
		return m.RemoveRelations
	}
	return nil
}

type Principal struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Principal) Reset()         { *m = Principal{} }
func (m *Principal) String() string { return proto.CompactTextString(m) }
func (*Principal) ProtoMessage()    {}
func (*Principal) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_7f6a95f507eac77c, []int{7}
}
func (m *Principal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Principal.Unmarshal(m, b)
}
func (m *Principal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Principal.Marshal(b, m, deterministic)
}
func (dst *Principal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Principal.Merge(dst, src)
}
func (m *Principal) XXX_Size() int {
	return xxx_messageInfo_Principal.Size(m)
}
func (m *Principal) XXX_DiscardUnknown() {
	xxx_messageInfo_Principal.DiscardUnknown(m)
}

var xxx_messageInfo_Principal proto.InternalMessageInfo

func (m *Principal) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Principal) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

type Principals struct {
	Users                []*Principal `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Groups               []*Principal `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Principals) Reset()         { *m = Principals{} }
func (m *Principals) String() string { return proto.CompactTextString(m) }
func (*Principals) ProtoMessage()    {}
func (*Principals) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_7f6a95f507eac77c, []int{8}
}
func (m *Principals) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Principals.Unmarshal(m, b)
}
func (m *Principals) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Principals.Marshal(b, m, deterministic)
}
func (dst *Principals) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Principals.Merge(dst, src)
}
func (m *Principals) XXX_Size() int {
	return xxx_messageInfo_Principals.Size(m)
}
func (m *Principals) XXX_DiscardUnknown() {
	xxx_messageInfo_Principals.DiscardUnknown(m)
}

var xxx_messageInfo_Principals proto.InternalMessageInfo

func (m *Principals) GetUsers() []*Principal {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Principals) GetGroups() []*Principal {
	if m != nil {
		return m.Groups
	}
	return nil
}

type StrategyResourceEntry struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace            *wrappers.StringValue `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StrategyResourceEntry) Reset()         { *m = StrategyResourceEntry{} }
func (m *StrategyResourceEntry) String() string { return proto.CompactTextString(m) }
func (*StrategyResourceEntry) ProtoMessage()    {}
func (*StrategyResourceEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_7f6a95f507eac77c, []int{9}
}
func (m *StrategyResourceEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrategyResourceEntry.Unmarshal(m, b)
}
func (m *StrategyResourceEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrategyResourceEntry.Marshal(b, m, deterministic)
}
func (dst *StrategyResourceEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrategyResourceEntry.Merge(dst, src)
}
func (m *StrategyResourceEntry) XXX_Size() int {
	return xxx_messageInfo_StrategyResourceEntry.Size(m)
}
func (m *StrategyResourceEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_StrategyResourceEntry.DiscardUnknown(m)
}

var xxx_messageInfo_StrategyResourceEntry proto.InternalMessageInfo

func (m *StrategyResourceEntry) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *StrategyResourceEntry) GetNamespace() *wrappers.StringValue {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *StrategyResourceEntry) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

type StrategyResources struct {
	StrategyId           *wrappers.StringValue    `protobuf:"bytes,1,opt,name=strategy_id,proto3" json:"strategy_id,omitempty"`
	Namespaces           []*StrategyResourceEntry `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Services             []*StrategyResourceEntry `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty"`
	ConfigGroups         []*StrategyResourceEntry `protobuf:"bytes,4,rep,name=config_groups,proto3" json:"config_groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *StrategyResources) Reset()         { *m = StrategyResources{} }
func (m *StrategyResources) String() string { return proto.CompactTextString(m) }
func (*StrategyResources) ProtoMessage()    {}
func (*StrategyResources) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_7f6a95f507eac77c, []int{10}
}
func (m *StrategyResources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrategyResources.Unmarshal(m, b)
}
func (m *StrategyResources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrategyResources.Marshal(b, m, deterministic)
}
func (dst *StrategyResources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrategyResources.Merge(dst, src)
}
func (m *StrategyResources) XXX_Size() int {
	return xxx_messageInfo_StrategyResources.Size(m)
}
func (m *StrategyResources) XXX_DiscardUnknown() {
	xxx_messageInfo_StrategyResources.DiscardUnknown(m)
}

var xxx_messageInfo_StrategyResources proto.InternalMessageInfo

func (m *StrategyResources) GetStrategyId() *wrappers.StringValue {
	if m != nil {
		return m.StrategyId
	}
	return nil
}

func (m *StrategyResources) GetNamespaces() []*StrategyResourceEntry {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

func (m *StrategyResources) GetServices() []*StrategyResourceEntry {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *StrategyResources) GetConfigGroups() []*StrategyResourceEntry {
	if m != nil {
		return m.ConfigGroups
	}
	return nil
}

type AuthStrategy struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Principals           *Principals           `protobuf:"bytes,3,opt,name=principals,proto3" json:"principals,omitempty"`
	Resources            *StrategyResources    `protobuf:"bytes,4,opt,name=resources,proto3" json:"resources,omitempty"`
	Action               AuthAction            `protobuf:"varint,5,opt,name=action,proto3,enum=v1.AuthAction" json:"action,omitempty"`
	Comment              *wrappers.StringValue `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	Owner                *wrappers.StringValue `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
	Ctime                *wrappers.StringValue `protobuf:"bytes,8,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Mtime                *wrappers.StringValue `protobuf:"bytes,9,opt,name=mtime,proto3" json:"mtime,omitempty"`
	AuthToken            *wrappers.StringValue `protobuf:"bytes,10,opt,name=auth_token,proto3" json:"auth_token,omitempty"`
	DefaultStrategy      *wrappers.BoolValue   `protobuf:"bytes,11,opt,name=default_strategy,proto3" json:"default_strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *AuthStrategy) Reset()         { *m = AuthStrategy{} }
func (m *AuthStrategy) String() string { return proto.CompactTextString(m) }
func (*AuthStrategy) ProtoMessage()    {}
func (*AuthStrategy) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_7f6a95f507eac77c, []int{11}
}
func (m *AuthStrategy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthStrategy.Unmarshal(m, b)
}
func (m *AuthStrategy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthStrategy.Marshal(b, m, deterministic)
}
func (dst *AuthStrategy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthStrategy.Merge(dst, src)
}
func (m *AuthStrategy) XXX_Size() int {
	return xxx_messageInfo_AuthStrategy.Size(m)
}
func (m *AuthStrategy) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthStrategy.DiscardUnknown(m)
}

var xxx_messageInfo_AuthStrategy proto.InternalMessageInfo

func (m *AuthStrategy) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *AuthStrategy) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *AuthStrategy) GetPrincipals() *Principals {
	if m != nil {
		return m.Principals
	}
	return nil
}

func (m *AuthStrategy) GetResources() *StrategyResources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *AuthStrategy) GetAction() AuthAction {
	if m != nil {
		return m.Action
	}
	return AuthAction_ONLY_READ
}

func (m *AuthStrategy) GetComment() *wrappers.StringValue {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *AuthStrategy) GetOwner() *wrappers.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *AuthStrategy) GetCtime() *wrappers.StringValue {
	if m != nil {
		return m.Ctime
	}
	return nil
}

func (m *AuthStrategy) GetMtime() *wrappers.StringValue {
	if m != nil {
		return m.Mtime
	}
	return nil
}

func (m *AuthStrategy) GetAuthToken() *wrappers.StringValue {
	if m != nil {
		return m.AuthToken
	}
	return nil
}

func (m *AuthStrategy) GetDefaultStrategy() *wrappers.BoolValue {
	if m != nil {
		return m.DefaultStrategy
	}
	return nil
}

type ModifyAuthStrategy struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AddPrincipals        *Principals           `protobuf:"bytes,3,opt,name=add_principals,proto3" json:"add_principals,omitempty"`
	RemovePrincipals     *Principals           `protobuf:"bytes,4,opt,name=remove_principals,proto3" json:"remove_principals,omitempty"`
	AddResources         *StrategyResources    `protobuf:"bytes,5,opt,name=add_resources,proto3" json:"add_resources,omitempty"`
	RemoveResources      *StrategyResources    `protobuf:"bytes,6,opt,name=remove_resources,proto3" json:"remove_resources,omitempty"`
	Action               AuthAction            `protobuf:"varint,7,opt,name=action,proto3,enum=v1.AuthAction" json:"action,omitempty"`
	Comment              *wrappers.StringValue `protobuf:"bytes,8,opt,name=comment,proto3" json:"comment,omitempty"`
	Owner                *wrappers.StringValue `protobuf:"bytes,9,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ModifyAuthStrategy) Reset()         { *m = ModifyAuthStrategy{} }
func (m *ModifyAuthStrategy) String() string { return proto.CompactTextString(m) }
func (*ModifyAuthStrategy) ProtoMessage()    {}
func (*ModifyAuthStrategy) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_7f6a95f507eac77c, []int{12}
}
func (m *ModifyAuthStrategy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyAuthStrategy.Unmarshal(m, b)
}
func (m *ModifyAuthStrategy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyAuthStrategy.Marshal(b, m, deterministic)
}
func (dst *ModifyAuthStrategy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyAuthStrategy.Merge(dst, src)
}
func (m *ModifyAuthStrategy) XXX_Size() int {
	return xxx_messageInfo_ModifyAuthStrategy.Size(m)
}
func (m *ModifyAuthStrategy) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyAuthStrategy.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyAuthStrategy proto.InternalMessageInfo

func (m *ModifyAuthStrategy) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ModifyAuthStrategy) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ModifyAuthStrategy) GetAddPrincipals() *Principals {
	if m != nil {
		return m.AddPrincipals
	}
	return nil
}

func (m *ModifyAuthStrategy) GetRemovePrincipals() *Principals {
	if m != nil {
		return m.RemovePrincipals
	}
	return nil
}

func (m *ModifyAuthStrategy) GetAddResources() *StrategyResources {
	if m != nil {
		return m.AddResources
	}
	return nil
}

func (m *ModifyAuthStrategy) GetRemoveResources() *StrategyResources {
	if m != nil {
		return m.RemoveResources
	}
	return nil
}

func (m *ModifyAuthStrategy) GetAction() AuthAction {
	if m != nil {
		return m.Action
	}
	return AuthAction_ONLY_READ
}

func (m *ModifyAuthStrategy) GetComment() *wrappers.StringValue {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *ModifyAuthStrategy) GetOwner() *wrappers.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "v1.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "v1.LoginResponse")
	proto.RegisterType((*User)(nil), "v1.User")
	proto.RegisterType((*ModifyUserPassword)(nil), "v1.ModifyUserPassword")
	proto.RegisterType((*UserGroupRelation)(nil), "v1.UserGroupRelation")
	proto.RegisterType((*UserGroup)(nil), "v1.UserGroup")
	proto.RegisterType((*ModifyUserGroup)(nil), "v1.ModifyUserGroup")
	proto.RegisterType((*Principal)(nil), "v1.Principal")
	proto.RegisterType((*Principals)(nil), "v1.Principals")
	proto.RegisterType((*StrategyResourceEntry)(nil), "v1.StrategyResourceEntry")
	proto.RegisterType((*StrategyResources)(nil), "v1.StrategyResources")
	proto.RegisterType((*AuthStrategy)(nil), "v1.AuthStrategy")
	proto.RegisterType((*ModifyAuthStrategy)(nil), "v1.ModifyAuthStrategy")
	proto.RegisterEnum("v1.AuthAction", AuthAction_name, AuthAction_value)
	proto.RegisterEnum("v1.ResourceType", ResourceType_name, ResourceType_value)
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_auth_7f6a95f507eac77c) }

var fileDescriptor_auth_7f6a95f507eac77c = []byte{
	// 979 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x57, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0xee, 0x7a, 0xbd, 0xbb, 0xf6, 0xc9, 0xee, 0xb2, 0x19, 0x29, 0x92, 0xa9, 0x50, 0x55, 0x19,
	0x81, 0xaa, 0x82, 0xb6, 0x4d, 0x02, 0x15, 0x94, 0x2a, 0x10, 0x20, 0xa0, 0x4a, 0xa5, 0x54, 0x4e,
	0xcb, 0xcf, 0x95, 0xe5, 0xec, 0x4e, 0xb6, 0x56, 0x6d, 0x8f, 0x99, 0x19, 0x27, 0xca, 0x0b, 0xf0,
	0x0e, 0xbc, 0x44, 0x6f, 0x78, 0x07, 0x2e, 0xb9, 0xe3, 0x8a, 0x77, 0x41, 0x68, 0xc6, 0x33, 0xde,
	0x75, 0x36, 0xdd, 0xcc, 0x3a, 0x0a, 0x12, 0x77, 0xab, 0xf1, 0xf7, 0x8d, 0xcf, 0xcf, 0x77, 0xbe,
	0xe3, 0x05, 0x88, 0x0a, 0xfe, 0x72, 0x9c, 0x53, 0xc2, 0x09, 0xb2, 0x4e, 0xb6, 0x6f, 0xde, 0x9a,
	0x11, 0x32, 0x4b, 0xf0, 0x3d, 0x79, 0x72, 0x54, 0x1c, 0xdf, 0x3b, 0xa5, 0x51, 0x9e, 0x63, 0xca,
	0x4a, 0x8c, 0xff, 0xba, 0x05, 0xfd, 0x27, 0x64, 0x16, 0x67, 0x01, 0xfe, 0xa5, 0xc0, 0x8c, 0xa3,
	0x1d, 0xe8, 0x90, 0xd3, 0x0c, 0x53, 0xaf, 0x75, 0xbb, 0x75, 0x67, 0x63, 0xe7, 0x9d, 0x71, 0x79,
	0xc1, 0x58, 0x5f, 0x30, 0x3e, 0xe4, 0x34, 0xce, 0x66, 0x3f, 0x44, 0x49, 0x81, 0x83, 0x12, 0x8a,
	0xee, 0x83, 0x9d, 0x45, 0x29, 0xf6, 0x2c, 0x03, 0x8a, 0x44, 0xa2, 0x4f, 0xc0, 0xc9, 0x23, 0xc6,
	0x4e, 0x09, 0x9d, 0x7a, 0x6d, 0x03, 0x56, 0x85, 0xf6, 0x7f, 0xb3, 0x60, 0xa0, 0x02, 0x66, 0x39,
	0xc9, 0x18, 0x46, 0x0f, 0xa0, 0x57, 0x30, 0x4c, 0xc3, 0x78, 0x6a, 0x14, 0xb3, 0x06, 0x37, 0x88,
	0xfa, 0x3e, 0xd8, 0x94, 0x24, 0xd8, 0x28, 0x62, 0x89, 0x14, 0x79, 0xca, 0x12, 0x89, 0xe0, 0x6c,
	0x93, 0x3c, 0x35, 0x5a, 0xf4, 0x81, 0x93, 0x57, 0x38, 0xf3, 0x3a, 0x26, 0x7d, 0x90, 0x50, 0xff,
	0xcf, 0x0e, 0xd8, 0x2f, 0x18, 0xa6, 0xe8, 0x43, 0xb0, 0x0c, 0xab, 0x61, 0x35, 0x2a, 0x44, 0xe3,
	0xf6, 0xcd, 0xe5, 0x65, 0x9b, 0xcb, 0xeb, 0x23, 0xe8, 0x32, 0x52, 0xd0, 0x09, 0x36, 0xaa, 0x85,
	0xc2, 0xa2, 0x47, 0xe5, 0x2c, 0x84, 0x65, 0x15, 0xbb, 0x06, 0xcc, 0x05, 0x3c, 0xda, 0x83, 0xbe,
	0xfc, 0x11, 0xe2, 0x2c, 0x3a, 0x4a, 0xb0, 0xd7, 0x93, 0xfc, 0x9b, 0x4b, 0xfc, 0x2f, 0x09, 0x49,
	0x4a, 0x76, 0x0d, 0x2f, 0x44, 0x39, 0x21, 0x69, 0x8a, 0x33, 0xee, 0x39, 0x26, 0xa2, 0x54, 0x60,
	0x51, 0x9f, 0x09, 0x8f, 0x53, 0xec, 0xb9, 0x26, 0xf5, 0x91, 0x50, 0xc1, 0x49, 0x25, 0x07, 0x4c,
	0x38, 0x12, 0x8a, 0x1e, 0x82, 0x2b, 0xe7, 0x80, 0x9f, 0xe5, 0xd8, 0xdb, 0x30, 0xe0, 0xcd, 0xe1,
	0xa2, 0x1f, 0x29, 0x39, 0x8a, 0x13, 0xec, 0xf5, 0x4d, 0xfa, 0x51, 0x62, 0x45, 0x94, 0x38, 0x8d,
	0xe2, 0xc4, 0x1b, 0x98, 0x44, 0x29, 0xa1, 0xfe, 0x1f, 0x2d, 0x40, 0xdf, 0x91, 0x69, 0x7c, 0x7c,
	0x26, 0x64, 0xfd, 0x4c, 0x8b, 0x68, 0x3d, 0x79, 0x7f, 0x01, 0x7d, 0x92, 0x4c, 0xc3, 0x4a, 0xb0,
	0x26, 0x32, 0xaf, 0x31, 0xc4, 0x0d, 0x19, 0x3e, 0x0d, 0xd7, 0x92, 0x7c, 0x8d, 0xe1, 0xa7, 0xb0,
	0x29, 0x32, 0xf8, 0x96, 0x92, 0x22, 0x0f, 0x70, 0x12, 0xf1, 0x98, 0x64, 0x62, 0x8a, 0x66, 0xe2,
	0xc0, 0xd4, 0xb9, 0x2a, 0x34, 0xba, 0x05, 0x1d, 0xd1, 0x0e, 0xe6, 0x59, 0xb7, 0xdb, 0x77, 0x36,
	0x76, 0x9c, 0xf1, 0xc9, 0xf6, 0x58, 0xdc, 0x1f, 0x94, 0xc7, 0xfe, 0x6b, 0x1b, 0xdc, 0xea, 0x7d,
	0xd7, 0xee, 0x06, 0xd5, 0x4c, 0xb7, 0xcd, 0x67, 0xba, 0x3e, 0x9d, 0xf6, 0x15, 0xa7, 0xb3, 0xd3,
	0x7c, 0x3a, 0xbb, 0x8d, 0xa6, 0xb3, 0xd7, 0x60, 0x3a, 0x1d, 0xf3, 0xe9, 0xdc, 0x06, 0x87, 0x2a,
	0x95, 0x28, 0x23, 0xd8, 0xd2, 0x2d, 0xae, 0x49, 0x28, 0xa8, 0x60, 0xa2, 0xa0, 0x72, 0x42, 0x27,
	0xa4, 0xc8, 0xf8, 0x1b, 0x9d, 0xe0, 0xc5, 0xe3, 0x8c, 0xef, 0xee, 0xa8, 0x82, 0xce, 0xf1, 0xfe,
	0xdf, 0x6d, 0x78, 0x6b, 0x3e, 0x68, 0x4d, 0x64, 0x53, 0x89, 0xc0, 0x5a, 0xff, 0xbb, 0xa1, 0x6d,
	0x2c, 0xb5, 0xff, 0xa7, 0x6c, 0x3e, 0x83, 0x41, 0x34, 0x9d, 0x86, 0xba, 0x57, 0x4c, 0xc9, 0xe7,
	0x0d, 0x3d, 0xad, 0x63, 0xd1, 0x3e, 0x8c, 0x28, 0x4e, 0xc9, 0x09, 0x5e, 0xe0, 0x3b, 0xab, 0xf8,
	0x4b, 0x70, 0xff, 0x15, 0xb8, 0xcf, 0x68, 0x9c, 0x4d, 0xe2, 0x3c, 0x4a, 0xae, 0xdb, 0x0d, 0xfc,
	0x9f, 0x00, 0xaa, 0x97, 0x31, 0xf4, 0xae, 0x76, 0xaa, 0x96, 0x74, 0xaa, 0x81, 0x08, 0xb9, 0x7a,
	0xac, 0xec, 0x0a, 0xbd, 0x07, 0x5d, 0x69, 0x6d, 0xda, 0xcf, 0xce, 0xa1, 0xd4, 0x43, 0xff, 0xf7,
	0x16, 0x6c, 0x1d, 0x72, 0x1a, 0x71, 0x3c, 0x3b, 0x0b, 0x70, 0xb9, 0xe6, 0x0f, 0x32, 0x4e, 0xcf,
	0xd6, 0xcc, 0xe9, 0x21, 0xb8, 0x22, 0x52, 0x96, 0x47, 0x13, 0xb3, 0xc4, 0xe6, 0xf0, 0xf5, 0x25,
	0xeb, 0xff, 0x6a, 0xc1, 0xe6, 0xf9, 0xa8, 0x19, 0xda, 0x83, 0x0d, 0xa6, 0x0e, 0x4d, 0xed, 0x7f,
	0x91, 0x80, 0x3e, 0x05, 0xa8, 0x82, 0xd2, 0x65, 0x7b, 0x5b, 0x94, 0xed, 0xc2, 0x02, 0x05, 0x0b,
	0x60, 0xf4, 0x31, 0x38, 0x0c, 0xd3, 0x93, 0x58, 0x10, 0xdb, 0x97, 0x11, 0x2b, 0x28, 0xfa, 0x1c,
	0x06, 0x13, 0x92, 0x1d, 0xc7, 0xb3, 0x50, 0xf5, 0xca, 0xbe, 0x8c, 0x5b, 0xc7, 0xfb, 0x7f, 0xd9,
	0xd0, 0xdf, 0x2f, 0xf8, 0x4b, 0x0d, 0xbe, 0xf6, 0xbd, 0x34, 0x06, 0xc8, 0x2b, 0x25, 0xaa, 0x8e,
	0x0d, 0x6b, 0xd2, 0x62, 0xc1, 0x02, 0x02, 0xed, 0x82, 0x4b, 0x75, 0x83, 0x94, 0xb7, 0x6c, 0x5d,
	0x94, 0x1d, 0x0b, 0xe6, 0x38, 0xf4, 0x3e, 0x74, 0xa3, 0x89, 0x34, 0x6a, 0xe1, 0x26, 0xc3, 0xf2,
	0x05, 0x22, 0xcd, 0x7d, 0x79, 0x1a, 0xa8, 0xa7, 0x57, 0x59, 0x39, 0xa5, 0xaf, 0xf6, 0xcc, 0x7d,
	0xb5, 0x5a, 0x53, 0x4e, 0x83, 0x35, 0xe5, 0x9a, 0xaf, 0xa9, 0xba, 0x1b, 0xc3, 0x9a, 0x6e, 0xfc,
	0x0d, 0x8c, 0xa6, 0xf8, 0x38, 0x2a, 0x12, 0x1e, 0x6a, 0x65, 0xab, 0x2f, 0xd1, 0x55, 0x8e, 0xbc,
	0xc4, 0xf1, 0xff, 0x69, 0xeb, 0x8f, 0xc4, 0xff, 0x54, 0x5d, 0x0f, 0x60, 0x28, 0x8c, 0xfa, 0x52,
	0x85, 0x9d, 0x43, 0xa1, 0x47, 0xb0, 0xa9, 0x0c, 0x7a, 0x81, 0x6a, 0x5f, 0x48, 0x5d, 0x06, 0xce,
	0x57, 0x89, 0xd6, 0x69, 0x67, 0x95, 0x4e, 0xeb, 0xd8, 0xda, 0x2a, 0xd1, 0xfc, 0xee, 0x2a, 0xfe,
	0x12, 0x7c, 0x41, 0xee, 0x3d, 0x53, 0xb9, 0x3b, 0x8d, 0xe4, 0xee, 0x1a, 0xcb, 0xfd, 0xee, 0x07,
	0x00, 0xf3, 0x08, 0xd0, 0x00, 0xdc, 0xef, 0x9f, 0x3e, 0xf9, 0x39, 0x0c, 0x0e, 0xf6, 0xbf, 0x1e,
	0xdd, 0x40, 0x43, 0x00, 0xf1, 0x2b, 0xfc, 0x31, 0x78, 0xfc, 0xfc, 0x60, 0xd4, 0xba, 0xbb, 0x07,
	0x7d, 0x9d, 0xdf, 0x73, 0xf1, 0x67, 0x66, 0x08, 0xf0, 0xb4, 0xf2, 0xc6, 0xd1, 0x0d, 0xd4, 0x07,
	0xe7, 0x50, 0x59, 0xde, 0xa8, 0x85, 0x46, 0xd0, 0xff, 0x4a, 0x9a, 0x98, 0x5c, 0xb1, 0x6c, 0x64,
	0x1d, 0x75, 0x65, 0x24, 0xbb, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x3a, 0x26, 0xec, 0x69,
	0x11, 0x00, 0x00,
}
