// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthAction int32

const (
	AuthAction_ONLY_ERAD  AuthAction = 0
	AuthAction_READ_WRITE AuthAction = 1
)

var AuthAction_name = map[int32]string{
	0: "ONLY_ERAD",
	1: "READ_WRITE",
}
var AuthAction_value = map[string]int32{
	"ONLY_ERAD":  0,
	"READ_WRITE": 1,
}

func (x AuthAction) String() string {
	return proto.EnumName(AuthAction_name, int32(x))
}
func (AuthAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_auth_37a29dfdd122469b, []int{0}
}

type ResourceType int32

const (
	ResourceType_Namespaces   ResourceType = 0
	ResourceType_Services     ResourceType = 1
	ResourceType_ConfigGroups ResourceType = 2
)

var ResourceType_name = map[int32]string{
	0: "Namespaces",
	1: "Services",
	2: "ConfigGroups",
}
var ResourceType_value = map[string]int32{
	"Namespaces":   0,
	"Services":     1,
	"ConfigGroups": 2,
}

func (x ResourceType) String() string {
	return proto.EnumName(ResourceType_name, int32(x))
}
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_auth_37a29dfdd122469b, []int{1}
}

type User struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password             *wrappers.StringValue `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Owner                *wrappers.StringValue `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Source               *wrappers.StringValue `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	AuthToken            *wrappers.StringValue `protobuf:"bytes,6,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	Comment              *wrappers.StringValue `protobuf:"bytes,7,opt,name=comment,proto3" json:"comment,omitempty"`
	Ctime                *wrappers.StringValue `protobuf:"bytes,8,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Mtime                *wrappers.StringValue `protobuf:"bytes,9,opt,name=mtime,proto3" json:"mtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_37a29dfdd122469b, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *User) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *User) GetPassword() *wrappers.StringValue {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *User) GetOwner() *wrappers.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *User) GetSource() *wrappers.StringValue {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *User) GetAuthToken() *wrappers.StringValue {
	if m != nil {
		return m.AuthToken
	}
	return nil
}

func (m *User) GetComment() *wrappers.StringValue {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *User) GetCtime() *wrappers.StringValue {
	if m != nil {
		return m.Ctime
	}
	return nil
}

func (m *User) GetMtime() *wrappers.StringValue {
	if m != nil {
		return m.Mtime
	}
	return nil
}

type UserToken struct {
	UserId               *wrappers.StringValue `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthToken            *wrappers.StringValue `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UserToken) Reset()         { *m = UserToken{} }
func (m *UserToken) String() string { return proto.CompactTextString(m) }
func (*UserToken) ProtoMessage()    {}
func (*UserToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_37a29dfdd122469b, []int{1}
}
func (m *UserToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserToken.Unmarshal(m, b)
}
func (m *UserToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserToken.Marshal(b, m, deterministic)
}
func (dst *UserToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserToken.Merge(dst, src)
}
func (m *UserToken) XXX_Size() int {
	return xxx_messageInfo_UserToken.Size(m)
}
func (m *UserToken) XXX_DiscardUnknown() {
	xxx_messageInfo_UserToken.DiscardUnknown(m)
}

var xxx_messageInfo_UserToken proto.InternalMessageInfo

func (m *UserToken) GetUserId() *wrappers.StringValue {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *UserToken) GetAuthToken() *wrappers.StringValue {
	if m != nil {
		return m.AuthToken
	}
	return nil
}

type UserGroup struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Owner                *wrappers.StringValue `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	AuthToken            *wrappers.StringValue `protobuf:"bytes,4,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	Comment              *wrappers.StringValue `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	Ctime                *wrappers.StringValue `protobuf:"bytes,6,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Mtime                *wrappers.StringValue `protobuf:"bytes,7,opt,name=mtime,proto3" json:"mtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UserGroup) Reset()         { *m = UserGroup{} }
func (m *UserGroup) String() string { return proto.CompactTextString(m) }
func (*UserGroup) ProtoMessage()    {}
func (*UserGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_37a29dfdd122469b, []int{2}
}
func (m *UserGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGroup.Unmarshal(m, b)
}
func (m *UserGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGroup.Marshal(b, m, deterministic)
}
func (dst *UserGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGroup.Merge(dst, src)
}
func (m *UserGroup) XXX_Size() int {
	return xxx_messageInfo_UserGroup.Size(m)
}
func (m *UserGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGroup.DiscardUnknown(m)
}

var xxx_messageInfo_UserGroup proto.InternalMessageInfo

func (m *UserGroup) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *UserGroup) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *UserGroup) GetOwner() *wrappers.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *UserGroup) GetAuthToken() *wrappers.StringValue {
	if m != nil {
		return m.AuthToken
	}
	return nil
}

func (m *UserGroup) GetComment() *wrappers.StringValue {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *UserGroup) GetCtime() *wrappers.StringValue {
	if m != nil {
		return m.Ctime
	}
	return nil
}

func (m *UserGroup) GetMtime() *wrappers.StringValue {
	if m != nil {
		return m.Mtime
	}
	return nil
}

type UserGroupRelation struct {
	GroupId              *wrappers.StringValue   `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserIds              []*wrappers.StringValue `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Join                 *wrappers.BoolValue     `protobuf:"bytes,3,opt,name=join,proto3" json:"join,omitempty"`
	AuthToken            *wrappers.StringValue   `protobuf:"bytes,4,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *UserGroupRelation) Reset()         { *m = UserGroupRelation{} }
func (m *UserGroupRelation) String() string { return proto.CompactTextString(m) }
func (*UserGroupRelation) ProtoMessage()    {}
func (*UserGroupRelation) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_37a29dfdd122469b, []int{3}
}
func (m *UserGroupRelation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGroupRelation.Unmarshal(m, b)
}
func (m *UserGroupRelation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGroupRelation.Marshal(b, m, deterministic)
}
func (dst *UserGroupRelation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGroupRelation.Merge(dst, src)
}
func (m *UserGroupRelation) XXX_Size() int {
	return xxx_messageInfo_UserGroupRelation.Size(m)
}
func (m *UserGroupRelation) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGroupRelation.DiscardUnknown(m)
}

var xxx_messageInfo_UserGroupRelation proto.InternalMessageInfo

func (m *UserGroupRelation) GetGroupId() *wrappers.StringValue {
	if m != nil {
		return m.GroupId
	}
	return nil
}

func (m *UserGroupRelation) GetUserIds() []*wrappers.StringValue {
	if m != nil {
		return m.UserIds
	}
	return nil
}

func (m *UserGroupRelation) GetJoin() *wrappers.BoolValue {
	if m != nil {
		return m.Join
	}
	return nil
}

func (m *UserGroupRelation) GetAuthToken() *wrappers.StringValue {
	if m != nil {
		return m.AuthToken
	}
	return nil
}

type Principal struct {
	Users                []*wrappers.StringValue `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Groups               []*wrappers.StringValue `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Principal) Reset()         { *m = Principal{} }
func (m *Principal) String() string { return proto.CompactTextString(m) }
func (*Principal) ProtoMessage()    {}
func (*Principal) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_37a29dfdd122469b, []int{4}
}
func (m *Principal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Principal.Unmarshal(m, b)
}
func (m *Principal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Principal.Marshal(b, m, deterministic)
}
func (dst *Principal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Principal.Merge(dst, src)
}
func (m *Principal) XXX_Size() int {
	return xxx_messageInfo_Principal.Size(m)
}
func (m *Principal) XXX_DiscardUnknown() {
	xxx_messageInfo_Principal.DiscardUnknown(m)
}

var xxx_messageInfo_Principal proto.InternalMessageInfo

func (m *Principal) GetUsers() []*wrappers.StringValue {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Principal) GetGroups() []*wrappers.StringValue {
	if m != nil {
		return m.Groups
	}
	return nil
}

type StrategyResource struct {
	StrategyId           *wrappers.StringValue   `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Namespaces           []*wrappers.StringValue `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Services             []*wrappers.StringValue `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty"`
	ConfigGroups         []*wrappers.StringValue `protobuf:"bytes,4,rep,name=config_groups,json=configGroups,proto3" json:"config_groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *StrategyResource) Reset()         { *m = StrategyResource{} }
func (m *StrategyResource) String() string { return proto.CompactTextString(m) }
func (*StrategyResource) ProtoMessage()    {}
func (*StrategyResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_37a29dfdd122469b, []int{5}
}
func (m *StrategyResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrategyResource.Unmarshal(m, b)
}
func (m *StrategyResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrategyResource.Marshal(b, m, deterministic)
}
func (dst *StrategyResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrategyResource.Merge(dst, src)
}
func (m *StrategyResource) XXX_Size() int {
	return xxx_messageInfo_StrategyResource.Size(m)
}
func (m *StrategyResource) XXX_DiscardUnknown() {
	xxx_messageInfo_StrategyResource.DiscardUnknown(m)
}

var xxx_messageInfo_StrategyResource proto.InternalMessageInfo

func (m *StrategyResource) GetStrategyId() *wrappers.StringValue {
	if m != nil {
		return m.StrategyId
	}
	return nil
}

func (m *StrategyResource) GetNamespaces() []*wrappers.StringValue {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

func (m *StrategyResource) GetServices() []*wrappers.StringValue {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *StrategyResource) GetConfigGroups() []*wrappers.StringValue {
	if m != nil {
		return m.ConfigGroups
	}
	return nil
}

type AuthStrategy struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Principal            *Principal            `protobuf:"bytes,3,opt,name=principal,proto3" json:"principal,omitempty"`
	Resource             *StrategyResource     `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Action               AuthAction            `protobuf:"varint,5,opt,name=action,proto3,enum=v1.AuthAction" json:"action,omitempty"`
	Comment              *wrappers.StringValue `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	Owner                *wrappers.StringValue `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
	Ctime                *wrappers.StringValue `protobuf:"bytes,8,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Mtime                *wrappers.StringValue `protobuf:"bytes,9,opt,name=mtime,proto3" json:"mtime,omitempty"`
	AuthToken            *wrappers.StringValue `protobuf:"bytes,10,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *AuthStrategy) Reset()         { *m = AuthStrategy{} }
func (m *AuthStrategy) String() string { return proto.CompactTextString(m) }
func (*AuthStrategy) ProtoMessage()    {}
func (*AuthStrategy) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_37a29dfdd122469b, []int{6}
}
func (m *AuthStrategy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthStrategy.Unmarshal(m, b)
}
func (m *AuthStrategy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthStrategy.Marshal(b, m, deterministic)
}
func (dst *AuthStrategy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthStrategy.Merge(dst, src)
}
func (m *AuthStrategy) XXX_Size() int {
	return xxx_messageInfo_AuthStrategy.Size(m)
}
func (m *AuthStrategy) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthStrategy.DiscardUnknown(m)
}

var xxx_messageInfo_AuthStrategy proto.InternalMessageInfo

func (m *AuthStrategy) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *AuthStrategy) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *AuthStrategy) GetPrincipal() *Principal {
	if m != nil {
		return m.Principal
	}
	return nil
}

func (m *AuthStrategy) GetResource() *StrategyResource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *AuthStrategy) GetAction() AuthAction {
	if m != nil {
		return m.Action
	}
	return AuthAction_ONLY_ERAD
}

func (m *AuthStrategy) GetComment() *wrappers.StringValue {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *AuthStrategy) GetOwner() *wrappers.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *AuthStrategy) GetCtime() *wrappers.StringValue {
	if m != nil {
		return m.Ctime
	}
	return nil
}

func (m *AuthStrategy) GetMtime() *wrappers.StringValue {
	if m != nil {
		return m.Mtime
	}
	return nil
}

func (m *AuthStrategy) GetAuthToken() *wrappers.StringValue {
	if m != nil {
		return m.AuthToken
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "v1.User")
	proto.RegisterType((*UserToken)(nil), "v1.UserToken")
	proto.RegisterType((*UserGroup)(nil), "v1.UserGroup")
	proto.RegisterType((*UserGroupRelation)(nil), "v1.UserGroupRelation")
	proto.RegisterType((*Principal)(nil), "v1.Principal")
	proto.RegisterType((*StrategyResource)(nil), "v1.StrategyResource")
	proto.RegisterType((*AuthStrategy)(nil), "v1.AuthStrategy")
	proto.RegisterEnum("v1.AuthAction", AuthAction_name, AuthAction_value)
	proto.RegisterEnum("v1.ResourceType", ResourceType_name, ResourceType_value)
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_auth_37a29dfdd122469b) }

var fileDescriptor_auth_37a29dfdd122469b = []byte{
	// 620 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x95, 0xcd, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x97, 0x34, 0x4b, 0x9a, 0x77, 0x5d, 0x15, 0x2c, 0x0e, 0xd1, 0x84, 0xd0, 0xd4, 0x03,
	0x42, 0x1b, 0xca, 0xb6, 0xf2, 0x29, 0xf1, 0x21, 0x15, 0x56, 0x4d, 0x95, 0xd0, 0x40, 0x69, 0x01,
	0x71, 0xaa, 0xb2, 0xc4, 0xcb, 0x02, 0x6d, 0x1c, 0xd9, 0x49, 0xab, 0x9d, 0xb8, 0x71, 0xe2, 0xff,
	0xe4, 0xce, 0x99, 0x03, 0x72, 0xec, 0x64, 0xa5, 0x1c, 0x70, 0x8b, 0xc6, 0xd5, 0xf9, 0x3d, 0x92,
	0xdf, 0xe7, 0x79, 0xfc, 0x06, 0x20, 0x28, 0xf2, 0x0b, 0x2f, 0xa3, 0x24, 0x27, 0x48, 0x9f, 0x1d,
	0xed, 0xdc, 0x8e, 0x09, 0x89, 0x27, 0xf8, 0xa0, 0x3c, 0x39, 0x2b, 0xce, 0x0f, 0xe6, 0x34, 0xc8,
	0x32, 0x4c, 0x99, 0x60, 0x3a, 0xdf, 0x1b, 0x60, 0xbc, 0x63, 0x98, 0xa2, 0x7b, 0xa0, 0x27, 0x91,
	0xab, 0xed, 0x6a, 0x77, 0xb7, 0xba, 0xb7, 0x3c, 0xa1, 0xf2, 0x2a, 0x95, 0x37, 0xcc, 0x69, 0x92,
	0xc6, 0xef, 0x83, 0x49, 0x81, 0x7d, 0x3d, 0x89, 0xd0, 0x21, 0x18, 0x69, 0x30, 0xc5, 0xae, 0xae,
	0xc0, 0x97, 0x24, 0x7a, 0x02, 0xcd, 0x2c, 0x60, 0x6c, 0x4e, 0x68, 0xe4, 0x36, 0x14, 0x54, 0x35,
	0x8d, 0xba, 0xb0, 0x49, 0xe6, 0x29, 0xa6, 0xae, 0xa1, 0x20, 0x13, 0x28, 0x7a, 0x00, 0x26, 0x23,
	0x05, 0x0d, 0xb1, 0xbb, 0xa9, 0x20, 0x92, 0x2c, 0x7a, 0x2a, 0xec, 0x1b, 0xe7, 0xe4, 0x33, 0x4e,
	0x5d, 0x53, 0x41, 0x69, 0x73, 0x7e, 0xc4, 0x71, 0xf4, 0x08, 0xac, 0x90, 0x4c, 0xa7, 0x38, 0xcd,
	0x5d, 0x4b, 0x41, 0x59, 0xc1, 0x7c, 0xbc, 0x30, 0x4f, 0xa6, 0xd8, 0x6d, 0xaa, 0x8c, 0x57, 0xa2,
	0x5c, 0x33, 0x2d, 0x35, 0xb6, 0x8a, 0xa6, 0x44, 0x3b, 0x5f, 0xc0, 0xe6, 0x41, 0x8b, 0xcb, 0x3e,
	0x04, 0xab, 0x60, 0x98, 0x8e, 0x15, 0x23, 0x37, 0x39, 0x3c, 0x88, 0x96, 0x0c, 0xd2, 0x57, 0x32,
	0xa8, 0xf3, 0x53, 0x17, 0x37, 0x38, 0xa1, 0xa4, 0xc8, 0xae, 0xbd, 0x6f, 0x75, 0x6b, 0x1a, 0xea,
	0xad, 0xf9, 0x7d, 0x3c, 0x63, 0xed, 0xfc, 0x37, 0xd7, 0xca, 0xdf, 0x5c, 0x23, 0x7f, 0x4b, 0x3d,
	0xff, 0x1f, 0x1a, 0xdc, 0xa8, 0xed, 0xf7, 0xf1, 0x24, 0xc8, 0x13, 0x92, 0xa2, 0xc7, 0xd0, 0x8c,
	0xf9, 0x81, 0x6a, 0x13, 0xac, 0x92, 0x1e, 0x44, 0x5c, 0x28, 0x1b, 0xc4, 0x5c, 0x7d, 0xb7, 0xf1,
	0x77, 0xa1, 0xa8, 0x10, 0x43, 0x1e, 0x18, 0x9f, 0x48, 0x92, 0xca, 0x5c, 0x76, 0xfe, 0x10, 0xbd,
	0x24, 0x64, 0x22, 0x83, 0xe4, 0xdc, 0x3f, 0x85, 0xd2, 0x29, 0xc0, 0x7e, 0x4b, 0x93, 0x34, 0x4c,
	0xb2, 0x60, 0xc2, 0x5d, 0xe3, 0x97, 0x60, 0xae, 0xa6, 0x70, 0x5f, 0x81, 0xf2, 0x45, 0x52, 0x4e,
	0xac, 0x36, 0xa4, 0x64, 0x3b, 0xdf, 0x74, 0x70, 0x86, 0x39, 0x0d, 0x72, 0x1c, 0x5f, 0xfa, 0x58,
	0x6e, 0x97, 0xe7, 0xb0, 0xc5, 0xe4, 0x99, 0xaa, 0xdb, 0x50, 0x09, 0x06, 0x11, 0x7a, 0x06, 0xc0,
	0x8b, 0xcd, 0xb2, 0x20, 0xc4, 0x6a, 0xb7, 0x59, 0xe0, 0xf9, 0xfa, 0x65, 0x98, 0xce, 0x12, 0xae,
	0x6d, 0x28, 0x68, 0x6b, 0x1a, 0xf5, 0x60, 0x3b, 0x24, 0xe9, 0x79, 0x12, 0x8f, 0xa5, 0x11, 0x86,
	0x82, 0xbc, 0x25, 0x24, 0x27, 0xc2, 0x8e, 0xaf, 0x06, 0xb4, 0x7a, 0x45, 0x7e, 0x51, 0x59, 0x72,
	0xed, 0x8f, 0x7f, 0x1f, 0xec, 0xac, 0x8a, 0x5d, 0x16, 0x6d, 0xdb, 0x9b, 0x1d, 0x79, 0x75, 0x17,
	0xfc, 0xab, 0xef, 0xe8, 0x10, 0x9a, 0x54, 0x66, 0x24, 0xeb, 0x75, 0x93, 0xb3, 0xcb, 0xf9, 0xf9,
	0x35, 0x85, 0xee, 0x80, 0x19, 0x84, 0xfc, 0xf9, 0x94, 0x2f, 0xbd, 0xdd, 0x6d, 0x73, 0x9e, 0x0f,
	0xd8, 0x2b, 0x4f, 0x7d, 0xf9, 0x75, 0x71, 0x25, 0x98, 0x2b, 0xae, 0x04, 0xb1, 0xbb, 0x2c, 0xf5,
	0xdd, 0xf5, 0x9f, 0x7e, 0x23, 0x4b, 0xcf, 0x11, 0x56, 0x7a, 0x8e, 0x7b, 0xfb, 0x00, 0x57, 0x36,
	0xa1, 0x6d, 0xb0, 0xdf, 0x9c, 0xbe, 0xfe, 0x38, 0xee, 0xfb, 0xbd, 0x63, 0x67, 0x03, 0xb5, 0x01,
	0xfc, 0x7e, 0xef, 0x78, 0xfc, 0xc1, 0x1f, 0x8c, 0xfa, 0x8e, 0xb6, 0xf7, 0x02, 0x5a, 0x95, 0xf7,
	0xa3, 0xcb, 0x0c, 0xf3, 0xef, 0xa7, 0x75, 0xa1, 0x9d, 0x0d, 0xd4, 0x82, 0xe6, 0x50, 0x96, 0xd4,
	0xd1, 0x90, 0x03, 0xad, 0x57, 0x0b, 0x9d, 0x73, 0xf4, 0x33, 0xb3, 0xbc, 0xcd, 0xfd, 0x5f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x1d, 0x95, 0x0f, 0x31, 0x13, 0x09, 0x00, 0x00,
}
