// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config_file_response.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConfigSimpleResponse struct {
	Code                 *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ConfigSimpleResponse) Reset()         { *m = ConfigSimpleResponse{} }
func (m *ConfigSimpleResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigSimpleResponse) ProtoMessage()    {}
func (*ConfigSimpleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_response_477e879754493a54, []int{0}
}
func (m *ConfigSimpleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigSimpleResponse.Unmarshal(m, b)
}
func (m *ConfigSimpleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigSimpleResponse.Marshal(b, m, deterministic)
}
func (dst *ConfigSimpleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigSimpleResponse.Merge(dst, src)
}
func (m *ConfigSimpleResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigSimpleResponse.Size(m)
}
func (m *ConfigSimpleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigSimpleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigSimpleResponse proto.InternalMessageInfo

func (m *ConfigSimpleResponse) GetCode() *wrappers.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *ConfigSimpleResponse) GetInfo() *wrappers.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

type ConfigResponse struct {
	Code                     *wrappers.UInt32Value     `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                     *wrappers.StringValue     `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	ConfigFileGroup          *ConfigFileGroup          `protobuf:"bytes,3,opt,name=configFileGroup,proto3" json:"configFileGroup,omitempty"`
	ConfigFile               *ConfigFile               `protobuf:"bytes,4,opt,name=configFile,proto3" json:"configFile,omitempty"`
	ConfigFileRelease        *ConfigFileRelease        `protobuf:"bytes,5,opt,name=configFileRelease,proto3" json:"configFileRelease,omitempty"`
	ConfigFileReleaseHistory *ConfigFileReleaseHistory `protobuf:"bytes,6,opt,name=configFileReleaseHistory,proto3" json:"configFileReleaseHistory,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                  `json:"-"`
	XXX_unrecognized         []byte                    `json:"-"`
	XXX_sizecache            int32                     `json:"-"`
}

func (m *ConfigResponse) Reset()         { *m = ConfigResponse{} }
func (m *ConfigResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigResponse) ProtoMessage()    {}
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_response_477e879754493a54, []int{1}
}
func (m *ConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigResponse.Unmarshal(m, b)
}
func (m *ConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigResponse.Marshal(b, m, deterministic)
}
func (dst *ConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigResponse.Merge(dst, src)
}
func (m *ConfigResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigResponse.Size(m)
}
func (m *ConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigResponse proto.InternalMessageInfo

func (m *ConfigResponse) GetCode() *wrappers.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *ConfigResponse) GetInfo() *wrappers.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ConfigResponse) GetConfigFileGroup() *ConfigFileGroup {
	if m != nil {
		return m.ConfigFileGroup
	}
	return nil
}

func (m *ConfigResponse) GetConfigFile() *ConfigFile {
	if m != nil {
		return m.ConfigFile
	}
	return nil
}

func (m *ConfigResponse) GetConfigFileRelease() *ConfigFileRelease {
	if m != nil {
		return m.ConfigFileRelease
	}
	return nil
}

func (m *ConfigResponse) GetConfigFileReleaseHistory() *ConfigFileReleaseHistory {
	if m != nil {
		return m.ConfigFileReleaseHistory
	}
	return nil
}

type ConfigBatchWriteResponse struct {
	Code                 *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Total                *wrappers.UInt32Value `protobuf:"bytes,3,opt,name=total,proto3" json:"total,omitempty"`
	Responses            []*ConfigResponse     `protobuf:"bytes,4,rep,name=responses,proto3" json:"responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ConfigBatchWriteResponse) Reset()         { *m = ConfigBatchWriteResponse{} }
func (m *ConfigBatchWriteResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigBatchWriteResponse) ProtoMessage()    {}
func (*ConfigBatchWriteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_response_477e879754493a54, []int{2}
}
func (m *ConfigBatchWriteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigBatchWriteResponse.Unmarshal(m, b)
}
func (m *ConfigBatchWriteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigBatchWriteResponse.Marshal(b, m, deterministic)
}
func (dst *ConfigBatchWriteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigBatchWriteResponse.Merge(dst, src)
}
func (m *ConfigBatchWriteResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigBatchWriteResponse.Size(m)
}
func (m *ConfigBatchWriteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigBatchWriteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigBatchWriteResponse proto.InternalMessageInfo

func (m *ConfigBatchWriteResponse) GetCode() *wrappers.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *ConfigBatchWriteResponse) GetInfo() *wrappers.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ConfigBatchWriteResponse) GetTotal() *wrappers.UInt32Value {
	if m != nil {
		return m.Total
	}
	return nil
}

func (m *ConfigBatchWriteResponse) GetResponses() []*ConfigResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

type ConfigBatchQueryResponse struct {
	Code                       *wrappers.UInt32Value       `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                       *wrappers.StringValue       `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Total                      *wrappers.UInt32Value       `protobuf:"bytes,3,opt,name=total,proto3" json:"total,omitempty"`
	ConfigFileGroups           []*ConfigFileGroup          `protobuf:"bytes,4,rep,name=configFileGroups,proto3" json:"configFileGroups,omitempty"`
	ConfigFiles                []*ConfigFile               `protobuf:"bytes,5,rep,name=configFiles,proto3" json:"configFiles,omitempty"`
	ConfigFileReleases         []*ConfigFileRelease        `protobuf:"bytes,6,rep,name=configFileReleases,proto3" json:"configFileReleases,omitempty"`
	ConfigFileReleaseHistories []*ConfigFileReleaseHistory `protobuf:"bytes,7,rep,name=configFileReleaseHistories,proto3" json:"configFileReleaseHistories,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                    `json:"-"`
	XXX_unrecognized           []byte                      `json:"-"`
	XXX_sizecache              int32                       `json:"-"`
}

func (m *ConfigBatchQueryResponse) Reset()         { *m = ConfigBatchQueryResponse{} }
func (m *ConfigBatchQueryResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigBatchQueryResponse) ProtoMessage()    {}
func (*ConfigBatchQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_response_477e879754493a54, []int{3}
}
func (m *ConfigBatchQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigBatchQueryResponse.Unmarshal(m, b)
}
func (m *ConfigBatchQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigBatchQueryResponse.Marshal(b, m, deterministic)
}
func (dst *ConfigBatchQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigBatchQueryResponse.Merge(dst, src)
}
func (m *ConfigBatchQueryResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigBatchQueryResponse.Size(m)
}
func (m *ConfigBatchQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigBatchQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigBatchQueryResponse proto.InternalMessageInfo

func (m *ConfigBatchQueryResponse) GetCode() *wrappers.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *ConfigBatchQueryResponse) GetInfo() *wrappers.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ConfigBatchQueryResponse) GetTotal() *wrappers.UInt32Value {
	if m != nil {
		return m.Total
	}
	return nil
}

func (m *ConfigBatchQueryResponse) GetConfigFileGroups() []*ConfigFileGroup {
	if m != nil {
		return m.ConfigFileGroups
	}
	return nil
}

func (m *ConfigBatchQueryResponse) GetConfigFiles() []*ConfigFile {
	if m != nil {
		return m.ConfigFiles
	}
	return nil
}

func (m *ConfigBatchQueryResponse) GetConfigFileReleases() []*ConfigFileRelease {
	if m != nil {
		return m.ConfigFileReleases
	}
	return nil
}

func (m *ConfigBatchQueryResponse) GetConfigFileReleaseHistories() []*ConfigFileReleaseHistory {
	if m != nil {
		return m.ConfigFileReleaseHistories
	}
	return nil
}

type ConfigClientResponse struct {
	Code                 *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	ConfigFile           *ClientConfigFileInfo `protobuf:"bytes,3,opt,name=configFile,proto3" json:"configFile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ConfigClientResponse) Reset()         { *m = ConfigClientResponse{} }
func (m *ConfigClientResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigClientResponse) ProtoMessage()    {}
func (*ConfigClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_response_477e879754493a54, []int{4}
}
func (m *ConfigClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigClientResponse.Unmarshal(m, b)
}
func (m *ConfigClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigClientResponse.Marshal(b, m, deterministic)
}
func (dst *ConfigClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigClientResponse.Merge(dst, src)
}
func (m *ConfigClientResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigClientResponse.Size(m)
}
func (m *ConfigClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigClientResponse proto.InternalMessageInfo

func (m *ConfigClientResponse) GetCode() *wrappers.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *ConfigClientResponse) GetInfo() *wrappers.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ConfigClientResponse) GetConfigFile() *ClientConfigFileInfo {
	if m != nil {
		return m.ConfigFile
	}
	return nil
}

func init() {
	proto.RegisterType((*ConfigSimpleResponse)(nil), "v1.ConfigSimpleResponse")
	proto.RegisterType((*ConfigResponse)(nil), "v1.ConfigResponse")
	proto.RegisterType((*ConfigBatchWriteResponse)(nil), "v1.ConfigBatchWriteResponse")
	proto.RegisterType((*ConfigBatchQueryResponse)(nil), "v1.ConfigBatchQueryResponse")
	proto.RegisterType((*ConfigClientResponse)(nil), "v1.ConfigClientResponse")
}

func init() {
	proto.RegisterFile("config_file_response.proto", fileDescriptor_config_file_response_477e879754493a54)
}

var fileDescriptor_config_file_response_477e879754493a54 = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0x5d, 0xab, 0xda, 0x30,
	0x1c, 0xc6, 0xa9, 0xad, 0x8e, 0x45, 0x70, 0x33, 0xdb, 0x20, 0xc8, 0x18, 0xd2, 0x2b, 0xaf, 0xaa,
	0xd6, 0x9b, 0xdd, 0x8c, 0x81, 0x65, 0x2f, 0x5e, 0x2e, 0xb2, 0x17, 0xc6, 0x40, 0xaa, 0x4b, 0xbb,
	0x40, 0xd6, 0x94, 0x24, 0x75, 0xb8, 0xcb, 0xf3, 0x99, 0xce, 0xa7, 0x38, 0x9f, 0xe3, 0x7c, 0x90,
	0x83, 0x49, 0x4b, 0xdf, 0xd4, 0x4b, 0x39, 0x97, 0xfe, 0xf3, 0xfc, 0x9e, 0xe4, 0x31, 0x4f, 0x03,
	0x46, 0x3b, 0x9e, 0x44, 0x34, 0xde, 0x44, 0x94, 0x91, 0x8d, 0x20, 0x32, 0xe5, 0x89, 0x24, 0x5e,
	0x2a, 0xb8, 0xe2, 0xb0, 0xb3, 0x9f, 0x8f, 0xde, 0xc4, 0x9c, 0xc7, 0x8c, 0x4c, 0xf5, 0x64, 0x9b,
	0x45, 0xd3, 0x7f, 0x22, 0x4c, 0x53, 0x22, 0xa4, 0xd1, 0x8c, 0x86, 0x15, 0xde, 0x8c, 0xdc, 0xff,
	0xe0, 0x65, 0xa0, 0x87, 0x6b, 0xfa, 0x37, 0x65, 0x04, 0xe7, 0xa6, 0x70, 0x06, 0x9c, 0x1d, 0xff,
	0x4d, 0x90, 0x35, 0xb6, 0x26, 0x7d, 0xff, 0xb5, 0x67, 0x9c, 0xbd, 0xc2, 0xd9, 0xfb, 0xba, 0x4a,
	0xd4, 0xc2, 0xff, 0x16, 0xb2, 0x8c, 0x60, 0xad, 0x3c, 0x12, 0x34, 0x89, 0x38, 0xea, 0x9c, 0x21,
	0xd6, 0x4a, 0xd0, 0x24, 0xce, 0x89, 0xa3, 0xd2, 0xbd, 0xb1, 0xc1, 0xc0, 0x6c, 0x7e, 0xcd, 0x6d,
	0xe1, 0x3b, 0xf0, 0xcc, 0xfc, 0x0f, 0x1f, 0x29, 0x23, 0x9f, 0x04, 0xcf, 0x52, 0x64, 0x6b, 0xf8,
	0x85, 0xb7, 0x9f, 0x7b, 0x41, 0x7d, 0x09, 0x37, 0xb5, 0xd0, 0x03, 0xa0, 0x1c, 0x21, 0x47, 0x93,
	0x83, 0x3a, 0x89, 0x2b, 0x0a, 0x18, 0x80, 0x61, 0xf9, 0x0b, 0x13, 0x46, 0x42, 0x49, 0x50, 0x57,
	0x63, 0xaf, 0x1a, 0x98, 0x59, 0xc4, 0x6d, 0x3d, 0xfc, 0x01, 0x50, 0x6b, 0xf8, 0x99, 0x4a, 0xc5,
	0xc5, 0x01, 0xf5, 0xf2, 0xe4, 0xa7, 0xbc, 0x72, 0x0d, 0x3e, 0x4b, 0xbb, 0xf7, 0x16, 0x40, 0x06,
	0x5b, 0x86, 0x6a, 0xf7, 0xe7, 0xbb, 0xa0, 0xea, 0xaa, 0x2d, 0x80, 0x3e, 0xe8, 0x2a, 0xae, 0x42,
	0x96, 0x5f, 0xc2, 0xe5, 0x4d, 0x8c, 0x14, 0xce, 0xc0, 0xd3, 0xa2, 0xfe, 0x12, 0x39, 0x63, 0x7b,
	0xd2, 0xf7, 0x61, 0x99, 0xbf, 0x38, 0x3e, 0x2e, 0x45, 0xee, 0x9d, 0x5d, 0x8b, 0xf9, 0x25, 0x23,
	0xe2, 0xf0, 0xe8, 0x63, 0xbe, 0x07, 0xcf, 0x1b, 0xed, 0x2b, 0xd2, 0x9e, 0xac, 0x6a, 0x4b, 0x0c,
	0x67, 0xa0, 0x5f, 0xce, 0x24, 0xea, 0x6a, 0xb6, 0x59, 0xd6, 0xaa, 0x04, 0x7e, 0x00, 0xb0, 0x55,
	0x15, 0x89, 0x7a, 0x1a, 0x3c, 0x53, 0xd7, 0x13, 0x00, 0xfc, 0x55, 0xbc, 0x55, 0xad, 0xc6, 0x51,
	0x22, 0xd1, 0x13, 0x6d, 0x77, 0xb9, 0xb1, 0x17, 0x78, 0xf7, 0xd6, 0x2a, 0x5e, 0xad, 0x80, 0x51,
	0x92, 0xa8, 0xab, 0x5e, 0xe4, 0xdb, 0xda, 0xf7, 0x6f, 0x6e, 0x13, 0xe9, 0x28, 0xfa, 0x2c, 0x65,
	0xa0, 0x55, 0x12, 0xf1, 0xea, 0x4b, 0xb0, 0x74, 0x7e, 0x76, 0xf6, 0xf3, 0x6d, 0x4f, 0x7b, 0x2f,
	0x1e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x8f, 0x39, 0x21, 0xcd, 0x05, 0x00, 0x00,
}
