// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DiscoverRequest_DiscoverRequestType int32

const (
	DiscoverRequest_UNKNOWN         DiscoverRequest_DiscoverRequestType = 0
	DiscoverRequest_INSTANCE        DiscoverRequest_DiscoverRequestType = 1
	DiscoverRequest_CLUSTER         DiscoverRequest_DiscoverRequestType = 2
	DiscoverRequest_ROUTING         DiscoverRequest_DiscoverRequestType = 3
	DiscoverRequest_RATE_LIMIT      DiscoverRequest_DiscoverRequestType = 4
	DiscoverRequest_CIRCUIT_BREAKER DiscoverRequest_DiscoverRequestType = 5
	DiscoverRequest_SERVICES        DiscoverRequest_DiscoverRequestType = 6
)

var DiscoverRequest_DiscoverRequestType_name = map[int32]string{
	0: "UNKNOWN",
	1: "INSTANCE",
	2: "CLUSTER",
	3: "ROUTING",
	4: "RATE_LIMIT",
	5: "CIRCUIT_BREAKER",
	6: "SERVICES",
}
var DiscoverRequest_DiscoverRequestType_value = map[string]int32{
	"UNKNOWN":         0,
	"INSTANCE":        1,
	"CLUSTER":         2,
	"ROUTING":         3,
	"RATE_LIMIT":      4,
	"CIRCUIT_BREAKER": 5,
	"SERVICES":        6,
}

func (x DiscoverRequest_DiscoverRequestType) String() string {
	return proto.EnumName(DiscoverRequest_DiscoverRequestType_name, int32(x))
}
func (DiscoverRequest_DiscoverRequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_request_89a70c847f5ccd5b, []int{0, 0}
}

type DiscoverRequest struct {
	Type                 DiscoverRequest_DiscoverRequestType `protobuf:"varint,1,opt,name=type,proto3,enum=v1.DiscoverRequest_DiscoverRequestType" json:"type,omitempty"`
	Service              *Service                            `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *DiscoverRequest) Reset()         { *m = DiscoverRequest{} }
func (m *DiscoverRequest) String() string { return proto.CompactTextString(m) }
func (*DiscoverRequest) ProtoMessage()    {}
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_89a70c847f5ccd5b, []int{0}
}
func (m *DiscoverRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoverRequest.Unmarshal(m, b)
}
func (m *DiscoverRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoverRequest.Marshal(b, m, deterministic)
}
func (dst *DiscoverRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoverRequest.Merge(dst, src)
}
func (m *DiscoverRequest) XXX_Size() int {
	return xxx_messageInfo_DiscoverRequest.Size(m)
}
func (m *DiscoverRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoverRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoverRequest proto.InternalMessageInfo

func (m *DiscoverRequest) GetType() DiscoverRequest_DiscoverRequestType {
	if m != nil {
		return m.Type
	}
	return DiscoverRequest_UNKNOWN
}

func (m *DiscoverRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func init() {
	proto.RegisterType((*DiscoverRequest)(nil), "v1.DiscoverRequest")
	proto.RegisterEnum("v1.DiscoverRequest_DiscoverRequestType", DiscoverRequest_DiscoverRequestType_name, DiscoverRequest_DiscoverRequestType_value)
}

func init() { proto.RegisterFile("request.proto", fileDescriptor_request_89a70c847f5ccd5b) }

var fileDescriptor_request_89a70c847f5ccd5b = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xbf, 0x4b, 0xc3, 0x40,
	0x14, 0xc7, 0xbd, 0x34, 0x6d, 0xc2, 0x8b, 0x6d, 0x1f, 0xd7, 0xa5, 0x38, 0x95, 0x80, 0xd8, 0x29,
	0xd0, 0x3a, 0x3a, 0xc5, 0xf3, 0x90, 0xb3, 0xf5, 0x0a, 0xef, 0x2e, 0x3a, 0x16, 0x2c, 0x37, 0x74,
	0x4a, 0x4c, 0x62, 0xa0, 0xa3, 0xf8, 0x8f, 0x4b, 0x1a, 0x5d, 0x42, 0xc7, 0xef, 0xaf, 0xcf, 0x83,
	0x07, 0xe3, 0xd2, 0x7d, 0x7e, 0xb9, 0xaa, 0x4e, 0x8a, 0x32, 0xaf, 0x73, 0xee, 0x35, 0xab, 0x9b,
	0x71, 0xe5, 0xca, 0xe6, 0x78, 0x70, 0x9d, 0x15, 0x7f, 0x7b, 0x30, 0x7d, 0x3a, 0x56, 0x87, 0xbc,
	0x71, 0x25, 0x75, 0x65, 0xfe, 0x00, 0x7e, 0x7d, 0x2a, 0xdc, 0x9c, 0x2d, 0xd8, 0x72, 0xb2, 0xbe,
	0x4b, 0x9a, 0x55, 0xd2, 0xab, 0xf4, 0xb5, 0x3d, 0x15, 0x8e, 0xce, 0x23, 0x7e, 0x0b, 0xc1, 0xdf,
	0x85, 0xb9, 0xb7, 0x60, 0xcb, 0x68, 0x1d, 0xb5, 0x7b, 0xd3, 0x59, 0xf4, 0x9f, 0xc5, 0x3f, 0x0c,
	0x66, 0x17, 0x20, 0x3c, 0x82, 0x20, 0xd3, 0x1b, 0xbd, 0x7b, 0xd7, 0x78, 0xc5, 0xaf, 0x21, 0x54,
	0xda, 0xd8, 0x54, 0x0b, 0x89, 0xac, 0x8d, 0xc4, 0x36, 0x33, 0x56, 0x12, 0x7a, 0xad, 0xa0, 0x5d,
	0x66, 0x95, 0x7e, 0xc6, 0x01, 0x9f, 0x00, 0x50, 0x6a, 0xe5, 0x7e, 0xab, 0x5e, 0x95, 0x45, 0x9f,
	0xcf, 0x60, 0x2a, 0x14, 0x89, 0x4c, 0xd9, 0xfd, 0x23, 0xc9, 0x74, 0x23, 0x09, 0x87, 0x2d, 0xcc,
	0x48, 0x7a, 0x53, 0x42, 0x1a, 0x1c, 0xc5, 0x7e, 0x18, 0x60, 0xf4, 0xe2, 0x87, 0x03, 0x1c, 0x7e,
	0x8c, 0xce, 0xaf, 0xb8, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x54, 0x58, 0xfb, 0xdf, 0x2e, 0x01,
	0x00, 0x00,
}
