// Code generated by protoc-gen-go. DO NOT EDIT.
// source: response.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DiscoverResponse_DiscoverResponseType int32

const (
	DiscoverResponse_UNKNOWN         DiscoverResponse_DiscoverResponseType = 0
	DiscoverResponse_INSTANCE        DiscoverResponse_DiscoverResponseType = 1
	DiscoverResponse_CLUSTER         DiscoverResponse_DiscoverResponseType = 2
	DiscoverResponse_ROUTING         DiscoverResponse_DiscoverResponseType = 3
	DiscoverResponse_RATE_LIMIT      DiscoverResponse_DiscoverResponseType = 4
	DiscoverResponse_CIRCUIT_BREAKER DiscoverResponse_DiscoverResponseType = 5
	DiscoverResponse_SERVICES        DiscoverResponse_DiscoverResponseType = 6
	DiscoverResponse_NAMESPACES      DiscoverResponse_DiscoverResponseType = 12
)

var DiscoverResponse_DiscoverResponseType_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "INSTANCE",
	2:  "CLUSTER",
	3:  "ROUTING",
	4:  "RATE_LIMIT",
	5:  "CIRCUIT_BREAKER",
	6:  "SERVICES",
	12: "NAMESPACES",
}
var DiscoverResponse_DiscoverResponseType_value = map[string]int32{
	"UNKNOWN":         0,
	"INSTANCE":        1,
	"CLUSTER":         2,
	"ROUTING":         3,
	"RATE_LIMIT":      4,
	"CIRCUIT_BREAKER": 5,
	"SERVICES":        6,
	"NAMESPACES":      12,
}

func (x DiscoverResponse_DiscoverResponseType) String() string {
	return proto.EnumName(DiscoverResponse_DiscoverResponseType_name, int32(x))
}
func (DiscoverResponse_DiscoverResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_response_fa138b2a9919ddc6, []int{4, 0}
}

type SimpleResponse struct {
	Code                 *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SimpleResponse) Reset()         { *m = SimpleResponse{} }
func (m *SimpleResponse) String() string { return proto.CompactTextString(m) }
func (*SimpleResponse) ProtoMessage()    {}
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_fa138b2a9919ddc6, []int{0}
}
func (m *SimpleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleResponse.Unmarshal(m, b)
}
func (m *SimpleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleResponse.Marshal(b, m, deterministic)
}
func (dst *SimpleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleResponse.Merge(dst, src)
}
func (m *SimpleResponse) XXX_Size() int {
	return xxx_messageInfo_SimpleResponse.Size(m)
}
func (m *SimpleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleResponse proto.InternalMessageInfo

func (m *SimpleResponse) GetCode() *wrappers.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *SimpleResponse) GetInfo() *wrappers.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

type Response struct {
	Code                 *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Client               *Client               `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"`
	Namespace            *Namespace            `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service              *Service              `protobuf:"bytes,5,opt,name=service,proto3" json:"service,omitempty"`
	Instance             *Instance             `protobuf:"bytes,6,opt,name=instance,proto3" json:"instance,omitempty"`
	Routing              *Routing              `protobuf:"bytes,7,opt,name=routing,proto3" json:"routing,omitempty"`
	Alias                *ServiceAlias         `protobuf:"bytes,8,opt,name=alias,proto3" json:"alias,omitempty"`
	RateLimit            *Rule                 `protobuf:"bytes,9,opt,name=rateLimit,proto3" json:"rateLimit,omitempty"`
	CircuitBreaker       *CircuitBreaker       `protobuf:"bytes,10,opt,name=circuitBreaker,proto3" json:"circuitBreaker,omitempty"`
	ConfigRelease        *ConfigRelease        `protobuf:"bytes,11,opt,name=configRelease,proto3" json:"configRelease,omitempty"`
	Platform             *Platform             `protobuf:"bytes,15,opt,name=platform,proto3" json:"platform,omitempty"`
	User                 *User                 `protobuf:"bytes,19,opt,name=user,proto3" json:"user,omitempty"`
	UserGroup            *UserGroup            `protobuf:"bytes,20,opt,name=userGroup,proto3" json:"userGroup,omitempty"`
	AuthStrategy         *AuthStrategy         `protobuf:"bytes,21,opt,name=authStrategy,proto3" json:"authStrategy,omitempty"`
	Relation             *UserGroupRelation    `protobuf:"bytes,22,opt,name=relation,proto3" json:"relation,omitempty"`
	LoginResponse        *LoginResponse        `protobuf:"bytes,23,opt,name=loginResponse,proto3" json:"loginResponse,omitempty"`
	ModifyAuthStrategy   *ModifyAuthStrategy   `protobuf:"bytes,24,opt,name=modifyAuthStrategy,proto3" json:"modifyAuthStrategy,omitempty"`
	ModifyUserGroup      *ModifyUserGroup      `protobuf:"bytes,25,opt,name=modifyUserGroup,proto3" json:"modifyUserGroup,omitempty"`
	Resources            *StrategyResources    `protobuf:"bytes,26,opt,name=resources,proto3" json:"resources,omitempty"`
	OptionSwitch         *OptionSwitch         `protobuf:"bytes,27,opt,name=optionSwitch,proto3" json:"optionSwitch,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_fa138b2a9919ddc6, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() *wrappers.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *Response) GetInfo() *wrappers.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *Response) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *Response) GetNamespace() *Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *Response) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *Response) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *Response) GetRouting() *Routing {
	if m != nil {
		return m.Routing
	}
	return nil
}

func (m *Response) GetAlias() *ServiceAlias {
	if m != nil {
		return m.Alias
	}
	return nil
}

func (m *Response) GetRateLimit() *Rule {
	if m != nil {
		return m.RateLimit
	}
	return nil
}

func (m *Response) GetCircuitBreaker() *CircuitBreaker {
	if m != nil {
		return m.CircuitBreaker
	}
	return nil
}

func (m *Response) GetConfigRelease() *ConfigRelease {
	if m != nil {
		return m.ConfigRelease
	}
	return nil
}

func (m *Response) GetPlatform() *Platform {
	if m != nil {
		return m.Platform
	}
	return nil
}

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetUserGroup() *UserGroup {
	if m != nil {
		return m.UserGroup
	}
	return nil
}

func (m *Response) GetAuthStrategy() *AuthStrategy {
	if m != nil {
		return m.AuthStrategy
	}
	return nil
}

func (m *Response) GetRelation() *UserGroupRelation {
	if m != nil {
		return m.Relation
	}
	return nil
}

func (m *Response) GetLoginResponse() *LoginResponse {
	if m != nil {
		return m.LoginResponse
	}
	return nil
}

func (m *Response) GetModifyAuthStrategy() *ModifyAuthStrategy {
	if m != nil {
		return m.ModifyAuthStrategy
	}
	return nil
}

func (m *Response) GetModifyUserGroup() *ModifyUserGroup {
	if m != nil {
		return m.ModifyUserGroup
	}
	return nil
}

func (m *Response) GetResources() *StrategyResources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *Response) GetOptionSwitch() *OptionSwitch {
	if m != nil {
		return m.OptionSwitch
	}
	return nil
}

type BatchWriteResponse struct {
	Code                 *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Size                 *wrappers.UInt32Value `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	Responses            []*Response           `protobuf:"bytes,4,rep,name=responses,proto3" json:"responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BatchWriteResponse) Reset()         { *m = BatchWriteResponse{} }
func (m *BatchWriteResponse) String() string { return proto.CompactTextString(m) }
func (*BatchWriteResponse) ProtoMessage()    {}
func (*BatchWriteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_fa138b2a9919ddc6, []int{2}
}
func (m *BatchWriteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchWriteResponse.Unmarshal(m, b)
}
func (m *BatchWriteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchWriteResponse.Marshal(b, m, deterministic)
}
func (dst *BatchWriteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchWriteResponse.Merge(dst, src)
}
func (m *BatchWriteResponse) XXX_Size() int {
	return xxx_messageInfo_BatchWriteResponse.Size(m)
}
func (m *BatchWriteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchWriteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchWriteResponse proto.InternalMessageInfo

func (m *BatchWriteResponse) GetCode() *wrappers.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *BatchWriteResponse) GetInfo() *wrappers.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *BatchWriteResponse) GetSize() *wrappers.UInt32Value {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *BatchWriteResponse) GetResponses() []*Response {
	if m != nil {
		return m.Responses
	}
	return nil
}

type BatchQueryResponse struct {
	Code                 *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Amount               *wrappers.UInt32Value `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Size                 *wrappers.UInt32Value `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	Namespaces           []*Namespace          `protobuf:"bytes,5,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Services             []*Service            `protobuf:"bytes,6,rep,name=services,proto3" json:"services,omitempty"`
	Instances            []*Instance           `protobuf:"bytes,7,rep,name=instances,proto3" json:"instances,omitempty"`
	Routings             []*Routing            `protobuf:"bytes,8,rep,name=routings,proto3" json:"routings,omitempty"`
	Aliases              []*ServiceAlias       `protobuf:"bytes,9,rep,name=aliases,proto3" json:"aliases,omitempty"`
	RateLimits           []*Rule               `protobuf:"bytes,10,rep,name=rateLimits,proto3" json:"rateLimits,omitempty"`
	ConfigWithServices   []*ConfigWithService  `protobuf:"bytes,11,rep,name=configWithServices,proto3" json:"configWithServices,omitempty"`
	Platforms            []*Platform           `protobuf:"bytes,15,rep,name=platforms,proto3" json:"platforms,omitempty"`
	Users                []*User               `protobuf:"bytes,18,rep,name=users,proto3" json:"users,omitempty"`
	UserGroups           []*UserGroup          `protobuf:"bytes,19,rep,name=userGroups,proto3" json:"userGroups,omitempty"`
	AuthStrategies       []*AuthStrategy       `protobuf:"bytes,20,rep,name=authStrategies,proto3" json:"authStrategies,omitempty"`
	Clients              []*Client             `protobuf:"bytes,21,rep,name=clients,proto3" json:"clients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BatchQueryResponse) Reset()         { *m = BatchQueryResponse{} }
func (m *BatchQueryResponse) String() string { return proto.CompactTextString(m) }
func (*BatchQueryResponse) ProtoMessage()    {}
func (*BatchQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_fa138b2a9919ddc6, []int{3}
}
func (m *BatchQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchQueryResponse.Unmarshal(m, b)
}
func (m *BatchQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchQueryResponse.Marshal(b, m, deterministic)
}
func (dst *BatchQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchQueryResponse.Merge(dst, src)
}
func (m *BatchQueryResponse) XXX_Size() int {
	return xxx_messageInfo_BatchQueryResponse.Size(m)
}
func (m *BatchQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchQueryResponse proto.InternalMessageInfo

func (m *BatchQueryResponse) GetCode() *wrappers.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *BatchQueryResponse) GetInfo() *wrappers.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *BatchQueryResponse) GetAmount() *wrappers.UInt32Value {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *BatchQueryResponse) GetSize() *wrappers.UInt32Value {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *BatchQueryResponse) GetNamespaces() []*Namespace {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

func (m *BatchQueryResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *BatchQueryResponse) GetInstances() []*Instance {
	if m != nil {
		return m.Instances
	}
	return nil
}

func (m *BatchQueryResponse) GetRoutings() []*Routing {
	if m != nil {
		return m.Routings
	}
	return nil
}

func (m *BatchQueryResponse) GetAliases() []*ServiceAlias {
	if m != nil {
		return m.Aliases
	}
	return nil
}

func (m *BatchQueryResponse) GetRateLimits() []*Rule {
	if m != nil {
		return m.RateLimits
	}
	return nil
}

func (m *BatchQueryResponse) GetConfigWithServices() []*ConfigWithService {
	if m != nil {
		return m.ConfigWithServices
	}
	return nil
}

func (m *BatchQueryResponse) GetPlatforms() []*Platform {
	if m != nil {
		return m.Platforms
	}
	return nil
}

func (m *BatchQueryResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *BatchQueryResponse) GetUserGroups() []*UserGroup {
	if m != nil {
		return m.UserGroups
	}
	return nil
}

func (m *BatchQueryResponse) GetAuthStrategies() []*AuthStrategy {
	if m != nil {
		return m.AuthStrategies
	}
	return nil
}

func (m *BatchQueryResponse) GetClients() []*Client {
	if m != nil {
		return m.Clients
	}
	return nil
}

type DiscoverResponse struct {
	Code                 *wrappers.UInt32Value                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *wrappers.StringValue                 `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Type                 DiscoverResponse_DiscoverResponseType `protobuf:"varint,3,opt,name=type,proto3,enum=v1.DiscoverResponse_DiscoverResponseType" json:"type,omitempty"`
	Service              *Service                              `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Instances            []*Instance                           `protobuf:"bytes,5,rep,name=instances,proto3" json:"instances,omitempty"`
	Routing              *Routing                              `protobuf:"bytes,6,opt,name=routing,proto3" json:"routing,omitempty"`
	RateLimit            *RateLimit                            `protobuf:"bytes,7,opt,name=rateLimit,proto3" json:"rateLimit,omitempty"`
	CircuitBreaker       *CircuitBreaker                       `protobuf:"bytes,8,opt,name=circuitBreaker,proto3" json:"circuitBreaker,omitempty"`
	Services             []*Service                            `protobuf:"bytes,9,rep,name=services,proto3" json:"services,omitempty"`
	Namespaces           []*Namespace                          `protobuf:"bytes,10,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *DiscoverResponse) Reset()         { *m = DiscoverResponse{} }
func (m *DiscoverResponse) String() string { return proto.CompactTextString(m) }
func (*DiscoverResponse) ProtoMessage()    {}
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_fa138b2a9919ddc6, []int{4}
}
func (m *DiscoverResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoverResponse.Unmarshal(m, b)
}
func (m *DiscoverResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoverResponse.Marshal(b, m, deterministic)
}
func (dst *DiscoverResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoverResponse.Merge(dst, src)
}
func (m *DiscoverResponse) XXX_Size() int {
	return xxx_messageInfo_DiscoverResponse.Size(m)
}
func (m *DiscoverResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoverResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoverResponse proto.InternalMessageInfo

func (m *DiscoverResponse) GetCode() *wrappers.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *DiscoverResponse) GetInfo() *wrappers.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *DiscoverResponse) GetType() DiscoverResponse_DiscoverResponseType {
	if m != nil {
		return m.Type
	}
	return DiscoverResponse_UNKNOWN
}

func (m *DiscoverResponse) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *DiscoverResponse) GetInstances() []*Instance {
	if m != nil {
		return m.Instances
	}
	return nil
}

func (m *DiscoverResponse) GetRouting() *Routing {
	if m != nil {
		return m.Routing
	}
	return nil
}

func (m *DiscoverResponse) GetRateLimit() *RateLimit {
	if m != nil {
		return m.RateLimit
	}
	return nil
}

func (m *DiscoverResponse) GetCircuitBreaker() *CircuitBreaker {
	if m != nil {
		return m.CircuitBreaker
	}
	return nil
}

func (m *DiscoverResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *DiscoverResponse) GetNamespaces() []*Namespace {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

func init() {
	proto.RegisterType((*SimpleResponse)(nil), "v1.SimpleResponse")
	proto.RegisterType((*Response)(nil), "v1.Response")
	proto.RegisterType((*BatchWriteResponse)(nil), "v1.BatchWriteResponse")
	proto.RegisterType((*BatchQueryResponse)(nil), "v1.BatchQueryResponse")
	proto.RegisterType((*DiscoverResponse)(nil), "v1.DiscoverResponse")
	proto.RegisterEnum("v1.DiscoverResponse_DiscoverResponseType", DiscoverResponse_DiscoverResponseType_name, DiscoverResponse_DiscoverResponseType_value)
}

func init() { proto.RegisterFile("response.proto", fileDescriptor_response_fa138b2a9919ddc6) }

var fileDescriptor_response_fa138b2a9919ddc6 = []byte{
	// 1091 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x5d, 0x6f, 0xdb, 0x36,
	0x17, 0x7e, 0xd3, 0xc8, 0xb6, 0x7c, 0xec, 0xda, 0x2a, 0x9d, 0xf4, 0xe5, 0xb2, 0xa2, 0x28, 0x8c,
	0xad, 0xcb, 0x5c, 0xcc, 0x5d, 0x92, 0x02, 0x1b, 0x06, 0xf4, 0xc2, 0x71, 0x94, 0xcc, 0xf9, 0x70,
	0x3a, 0xca, 0x4e, 0x76, 0x17, 0x28, 0x0a, 0xe3, 0x10, 0x93, 0x25, 0x83, 0x94, 0x52, 0x64, 0xff,
	0xa2, 0xbf, 0x6a, 0x77, 0xbb, 0xdc, 0xef, 0x19, 0x48, 0x7d, 0x50, 0x76, 0x32, 0xb7, 0x57, 0xb9,
	0xb1, 0xc5, 0xf3, 0x3c, 0x87, 0xe4, 0x39, 0x3c, 0xe7, 0x39, 0xd0, 0xe0, 0x54, 0xcc, 0xc2, 0x40,
	0xd0, 0xee, 0x8c, 0x87, 0x51, 0x88, 0x9e, 0xdc, 0x6e, 0x6d, 0xbc, 0x9c, 0x84, 0xe1, 0xc4, 0xa7,
	0x6f, 0x95, 0xe5, 0x32, 0xbe, 0x7e, 0xfb, 0x91, 0xbb, 0xb3, 0x19, 0xe5, 0x22, 0xe1, 0x6c, 0x3c,
	0x15, 0x94, 0xdf, 0x32, 0x8f, 0x66, 0x4b, 0x1e, 0xc6, 0x11, 0x0b, 0x26, 0xe9, 0xb2, 0xee, 0xf9,
	0x8c, 0x06, 0x51, 0xba, 0x6a, 0x72, 0x37, 0xa2, 0x3e, 0x9b, 0xb2, 0xcc, 0xb0, 0xe6, 0x31, 0xee,
	0xc5, 0x2c, 0xba, 0xe4, 0xd4, 0xfd, 0x83, 0xf2, 0xd4, 0xda, 0xf2, 0xc2, 0xe0, 0x9a, 0x4d, 0x38,
	0xf5, 0xa9, 0x9b, 0xdd, 0x65, 0xa3, 0x31, 0xf3, 0xdd, 0xe8, 0x3a, 0xe4, 0xd3, 0x74, 0x0d, 0x6e,
	0x1c, 0xdd, 0xa4, 0xdf, 0xb5, 0x69, 0x78, 0x45, 0xfd, 0x64, 0xd1, 0x8e, 0xa0, 0xe1, 0xb0, 0xe9,
	0xcc, 0xa7, 0x24, 0x0d, 0x06, 0xfd, 0x08, 0x86, 0x17, 0x5e, 0x51, 0xbc, 0xf2, 0x6a, 0x65, 0xb3,
	0xb6, 0xfd, 0xa2, 0x9b, 0x44, 0xd4, 0xcd, 0x22, 0xea, 0x8e, 0x07, 0x41, 0xb4, 0xb3, 0x7d, 0xe6,
	0xfa, 0x31, 0x25, 0x8a, 0x29, 0x3d, 0x58, 0x70, 0x1d, 0xe2, 0x27, 0xff, 0xe1, 0xe1, 0x44, 0x9c,
	0x05, 0x93, 0xd4, 0x43, 0x32, 0xdb, 0x9f, 0x4c, 0x30, 0x1f, 0xf3, 0x40, 0xd4, 0x86, 0x72, 0x92,
	0x5b, 0xbc, 0xaa, 0x7c, 0xa0, 0x7b, 0xbb, 0xd5, 0xed, 0x2b, 0x0b, 0x49, 0x11, 0xf4, 0x06, 0xaa,
	0x81, 0x3b, 0xa5, 0x62, 0xe6, 0x7a, 0x14, 0x1b, 0x8a, 0xf6, 0x54, 0xd2, 0x86, 0x99, 0x91, 0x68,
	0x1c, 0x7d, 0x0b, 0x95, 0xf4, 0x29, 0x71, 0x49, 0x51, 0x6b, 0x92, 0xea, 0x24, 0x26, 0x92, 0x61,
	0x68, 0x13, 0x4c, 0x16, 0x88, 0xc8, 0x0d, 0x3c, 0x8a, 0xcb, 0x8a, 0x57, 0x97, 0xbc, 0x41, 0x6a,
	0x23, 0x39, 0x2a, 0x37, 0x4c, 0x8b, 0x01, 0x57, 0xf4, 0x86, 0x24, 0x31, 0x91, 0x0c, 0x43, 0xaf,
	0xa1, 0xe4, 0xfa, 0xcc, 0x15, 0xd8, 0x54, 0x24, 0xab, 0x70, 0x6a, 0x4f, 0xda, 0x49, 0x02, 0xa3,
	0xd7, 0x50, 0x95, 0xe5, 0x73, 0x2c, 0xcb, 0x07, 0x57, 0x15, 0xd7, 0x54, 0x1b, 0xc6, 0x3e, 0x25,
	0x1a, 0x42, 0xbf, 0x40, 0x23, 0xad, 0xaa, 0xdd, 0xa4, 0xaa, 0x30, 0x28, 0x32, 0x52, 0x09, 0x9a,
	0x43, 0xc8, 0x02, 0x13, 0xfd, 0x04, 0x4f, 0x93, 0xda, 0x23, 0x49, 0xed, 0xe1, 0x9a, 0x72, 0x7d,
	0xa6, 0x5c, 0x8b, 0x00, 0x99, 0xe7, 0xc9, 0xac, 0x64, 0xf5, 0x89, 0x9b, 0x3a, 0x2b, 0x1f, 0x52,
	0x1b, 0xc9, 0x51, 0xf4, 0x02, 0x8c, 0x58, 0x50, 0x8e, 0x5b, 0x3a, 0x82, 0xb1, 0xa0, 0x9c, 0x28,
	0xab, 0x7c, 0x31, 0xf9, 0x7f, 0xc0, 0xc3, 0x78, 0x86, 0xd7, 0xf4, 0x8b, 0x8d, 0x33, 0x23, 0xd1,
	0x38, 0x7a, 0x07, 0x75, 0xd9, 0x04, 0x4e, 0x24, 0x83, 0x9f, 0xdc, 0xe1, 0x75, 0x9d, 0xc0, 0x5e,
	0xc1, 0x4e, 0xe6, 0x58, 0x68, 0x0b, 0x4c, 0x4e, 0x7d, 0x37, 0x62, 0x61, 0x80, 0x9f, 0x2b, 0x8f,
	0xf5, 0xf9, 0x13, 0x52, 0x90, 0xe4, 0x34, 0x99, 0x16, 0x3f, 0x9c, 0xb0, 0x20, 0x2b, 0x70, 0xfc,
	0x7f, 0x9d, 0x96, 0xe3, 0x22, 0x40, 0xe6, 0x79, 0x68, 0x1f, 0xd0, 0x34, 0xbc, 0x62, 0xd7, 0x77,
	0xc5, 0xfb, 0x60, 0xac, 0xbc, 0x9f, 0x4b, 0xef, 0x93, 0x7b, 0x28, 0x79, 0xc0, 0x03, 0xbd, 0x87,
	0x66, 0x62, 0xcd, 0x6f, 0x89, 0xbf, 0x52, 0x9b, 0xb4, 0xf4, 0x26, 0x3a, 0x80, 0x45, 0x2e, 0xda,
	0x81, 0x2a, 0xa7, 0x22, 0x8c, 0xb9, 0x47, 0x05, 0xde, 0xd0, 0x31, 0xe7, 0x67, 0x66, 0x20, 0xd1,
	0x3c, 0x99, 0xdd, 0x70, 0x26, 0xc3, 0x77, 0x3e, 0xb2, 0xc8, 0xbb, 0xc1, 0x5f, 0xeb, 0xec, 0x9e,
	0x16, 0xec, 0x64, 0x8e, 0x75, 0x68, 0x98, 0x75, 0xab, 0x79, 0x68, 0x98, 0x96, 0xd5, 0x6a, 0xff,
	0xb3, 0x02, 0x68, 0xd7, 0x8d, 0xbc, 0x9b, 0x73, 0xce, 0xa2, 0x47, 0x95, 0x23, 0xe9, 0x21, 0xd8,
	0x9f, 0x34, 0xd5, 0x86, 0xcf, 0x9c, 0x21, 0x99, 0xa8, 0xa3, 0x72, 0xa4, 0x6e, 0x28, 0xb0, 0xf1,
	0x6a, 0x35, 0x2b, 0xe1, 0xfc, 0x69, 0x35, 0xdc, 0xfe, 0x54, 0x4e, 0x03, 0xfb, 0x2d, 0xa6, 0xfc,
	0xee, 0x51, 0x03, 0x7b, 0x07, 0x65, 0x77, 0x1a, 0xc6, 0xb9, 0xec, 0x2d, 0x3f, 0x25, 0xe5, 0xe6,
	0xe9, 0x30, 0xbe, 0x38, 0x1d, 0x3f, 0x00, 0xe4, 0xd2, 0x28, 0x70, 0x49, 0xe5, 0x63, 0x41, 0x3b,
	0x0b, 0x04, 0xf4, 0x1d, 0x98, 0xa9, 0x40, 0x0a, 0x5c, 0x56, 0xe4, 0x39, 0xf5, 0xcc, 0x41, 0x99,
	0xe6, 0x4c, 0x20, 0x05, 0xae, 0xe8, 0x34, 0xe7, 0xfa, 0xa9, 0x61, 0xb9, 0x69, 0x2a, 0x92, 0x52,
	0x1c, 0x57, 0x17, 0x15, 0x34, 0x07, 0x51, 0x07, 0x2a, 0x4a, 0x23, 0xa9, 0xc0, 0x55, 0xc5, 0xbb,
	0x2f, 0xa2, 0x19, 0x01, 0x6d, 0x02, 0xe4, 0x5a, 0x29, 0x30, 0x28, 0xba, 0xd6, 0xd1, 0x02, 0x86,
	0x6c, 0x40, 0x89, 0xc8, 0x9d, 0xb3, 0xe8, 0xc6, 0xc9, 0xa2, 0xab, 0x29, 0x8f, 0x75, 0xad, 0x88,
	0x05, 0x94, 0x3c, 0xe0, 0x20, 0x23, 0xce, 0xc4, 0x4f, 0xe0, 0xa6, 0x8e, 0x38, 0xd7, 0x46, 0x0d,
	0xa3, 0x97, 0x50, 0x92, 0xf2, 0x26, 0x30, 0xd2, 0xf7, 0x52, 0xea, 0x98, 0x98, 0xe5, 0xab, 0xe4,
	0xf2, 0x27, 0x70, 0x4b, 0xbf, 0x8a, 0x6e, 0xfe, 0x02, 0x01, 0xfd, 0x0c, 0x8d, 0x82, 0xf4, 0x31,
	0x2a, 0xf0, 0x9a, 0x4e, 0xcf, 0x9c, 0xe8, 0x2c, 0xf0, 0xd0, 0x37, 0x50, 0x49, 0x66, 0xa8, 0xc0,
	0xeb, 0xca, 0xa5, 0x38, 0x5e, 0x33, 0xa8, 0xd0, 0xec, 0xcf, 0xda, 0x7f, 0x95, 0xc0, 0xda, 0x63,
	0xc2, 0x0b, 0x6f, 0x29, 0x7f, 0xd4, 0x8e, 0x78, 0x0f, 0x46, 0x74, 0x37, 0x4b, 0x5a, 0xbd, 0xb1,
	0xfd, 0xbd, 0xbc, 0xe7, 0xe2, 0x3d, 0xee, 0x19, 0x46, 0x77, 0x33, 0x4a, 0x94, 0x5b, 0x71, 0xec,
	0x1b, 0x4b, 0xc6, 0xfe, 0x5c, 0xdd, 0x96, 0x96, 0xd7, 0x6d, 0x61, 0xf0, 0x97, 0x97, 0x0c, 0xfe,
	0x37, 0xc5, 0x81, 0x5e, 0xd1, 0xb3, 0x8e, 0x64, 0xc6, 0xe5, 0x53, 0xdd, 0xfc, 0xe2, 0xa9, 0x5e,
	0x6c, 0xce, 0xea, 0xb2, 0xe6, 0x9c, 0x6f, 0x7a, 0xf8, 0x4c, 0xd3, 0xb7, 0xff, 0x5e, 0x81, 0xb5,
	0x87, 0x32, 0x8b, 0x6a, 0x50, 0x19, 0x0f, 0x8f, 0x86, 0xa7, 0xe7, 0x43, 0xeb, 0x7f, 0xa8, 0x0e,
	0xe6, 0x60, 0xe8, 0x8c, 0x7a, 0xc3, 0xbe, 0x6d, 0xad, 0x48, 0xa8, 0x7f, 0x3c, 0x76, 0x46, 0x36,
	0xb1, 0x9e, 0xc8, 0x05, 0x39, 0x1d, 0x8f, 0x06, 0xc3, 0x03, 0x6b, 0x15, 0x35, 0x00, 0x48, 0x6f,
	0x64, 0x5f, 0x1c, 0x0f, 0x4e, 0x06, 0x23, 0xcb, 0x40, 0x2d, 0x68, 0xf6, 0x07, 0xa4, 0x3f, 0x1e,
	0x8c, 0x2e, 0x76, 0x89, 0xdd, 0x3b, 0xb2, 0x89, 0x55, 0x92, 0x9b, 0x39, 0x36, 0x39, 0x1b, 0xf4,
	0x6d, 0xc7, 0x2a, 0x4b, 0x97, 0x61, 0xef, 0xc4, 0x76, 0x3e, 0xf4, 0xe4, 0xba, 0xde, 0x36, 0xcc,
	0x8a, 0x55, 0xeb, 0x18, 0x27, 0xb6, 0xf3, 0x6b, 0xa7, 0x26, 0x7f, 0x2f, 0xfa, 0xa7, 0xc3, 0xfd,
	0xc1, 0x41, 0xa7, 0xb1, 0x7f, 0x3c, 0xfe, 0xfd, 0x62, 0x6f, 0x97, 0xd8, 0xfb, 0x44, 0x82, 0xa6,
	0x5a, 0x3b, 0x7b, 0x47, 0x9d, 0x5a, 0xf2, 0x65, 0x93, 0x33, 0x9b, 0x1c, 0x1a, 0x66, 0xcd, 0x6a,
	0x5c, 0x96, 0x55, 0xb1, 0xed, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x40, 0xf0, 0x06, 0x0e,
	0x0c, 0x00, 0x00,
}
