apiVersion: v1
kind: ConfigMap
metadata:
  name: polaris-console-config
  namespace: {{ .Values.installation.namespace }}
data:
  polaris-console.yaml: |-
    logger:
      RotateOutputPath: log/polaris-console.log
      RotationMaxSize: 500
      RotationMaxAge: 30
      RotationMaxBackups: 100
      level: info
    webServer:
      mode: "release"
      listenIP: "0.0.0.0"
      listenPort: {{ .Values.service.webPort }}
      jwt:
        secretKey: "${JWT_KEY}"
        expired: 1800
      namingV1URL: "/naming/v1"
      namingV2URL: "/naming/v2"
      authURL: "/core/v1"
      configURL: "/config/v1"
      monitorURL: "/api/v1"
      webPath: "web/dist/"
    polarisServer:
      address: "127.0.0.1:{{ .Values.service.httpPort }}"
      polarisToken: "nu/0WRA4EqSR1FagrjRj0fZwPXuGlMpX+zCuWu4uMqy8xr1vRjisSbA25aAC3mtU8MeeRsKhQiDAynUR09I="
    monitorServer:
      address: "polaris-prometheus:9090"
