// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model_v2.proto

package v2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MatchString_MatchStringType int32

const (
	// Equivalent match
	MatchString_EXACT MatchString_MatchStringType = 0
	// Regular match
	MatchString_REGEX MatchString_MatchStringType = 1
	// Not equals match
	MatchString_NOT_EQUALS MatchString_MatchStringType = 2
	// Include match
	MatchString_IN MatchString_MatchStringType = 3
	// Not include match
	MatchString_NOT_IN MatchString_MatchStringType = 4
)

var MatchString_MatchStringType_name = map[int32]string{
	0: "EXACT",
	1: "REGEX",
	2: "NOT_EQUALS",
	3: "IN",
	4: "NOT_IN",
}
var MatchString_MatchStringType_value = map[string]int32{
	"EXACT":      0,
	"REGEX":      1,
	"NOT_EQUALS": 2,
	"IN":         3,
	"NOT_IN":     4,
}

func (x MatchString_MatchStringType) String() string {
	return proto.EnumName(MatchString_MatchStringType_name, int32(x))
}
func (MatchString_MatchStringType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_model_v2_63fbe5e126956d10, []int{0, 0}
}

type MatchString_ValueType int32

const (
	MatchString_TEXT      MatchString_ValueType = 0
	MatchString_PARAMETER MatchString_ValueType = 1
	MatchString_VARIABLE  MatchString_ValueType = 2
)

var MatchString_ValueType_name = map[int32]string{
	0: "TEXT",
	1: "PARAMETER",
	2: "VARIABLE",
}
var MatchString_ValueType_value = map[string]int32{
	"TEXT":      0,
	"PARAMETER": 1,
	"VARIABLE":  2,
}

func (x MatchString_ValueType) String() string {
	return proto.EnumName(MatchString_ValueType_name, int32(x))
}
func (MatchString_ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_model_v2_63fbe5e126956d10, []int{0, 1}
}

// MatchString 这里的序号需要保证和 v1.MatchSrting 保持一致
type MatchString struct {
	Type                 MatchString_MatchStringType `protobuf:"varint,1,opt,name=type,proto3,enum=v2.MatchString_MatchStringType" json:"type,omitempty"`
	Value                *wrappers.StringValue       `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ValueType            MatchString_ValueType       `protobuf:"varint,3,opt,name=value_type,json=valueType,proto3,enum=v2.MatchString_ValueType" json:"value_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *MatchString) Reset()         { *m = MatchString{} }
func (m *MatchString) String() string { return proto.CompactTextString(m) }
func (*MatchString) ProtoMessage()    {}
func (*MatchString) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_v2_63fbe5e126956d10, []int{0}
}
func (m *MatchString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchString.Unmarshal(m, b)
}
func (m *MatchString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchString.Marshal(b, m, deterministic)
}
func (dst *MatchString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchString.Merge(dst, src)
}
func (m *MatchString) XXX_Size() int {
	return xxx_messageInfo_MatchString.Size(m)
}
func (m *MatchString) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchString.DiscardUnknown(m)
}

var xxx_messageInfo_MatchString proto.InternalMessageInfo

func (m *MatchString) GetType() MatchString_MatchStringType {
	if m != nil {
		return m.Type
	}
	return MatchString_EXACT
}

func (m *MatchString) GetValue() *wrappers.StringValue {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *MatchString) GetValueType() MatchString_ValueType {
	if m != nil {
		return m.ValueType
	}
	return MatchString_TEXT
}

func init() {
	proto.RegisterType((*MatchString)(nil), "v2.MatchString")
	proto.RegisterEnum("v2.MatchString_MatchStringType", MatchString_MatchStringType_name, MatchString_MatchStringType_value)
	proto.RegisterEnum("v2.MatchString_ValueType", MatchString_ValueType_name, MatchString_ValueType_value)
}

func init() { proto.RegisterFile("model_v2.proto", fileDescriptor_model_v2_63fbe5e126956d10) }

var fileDescriptor_model_v2_63fbe5e126956d10 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0x80, 0x6d, 0xd6, 0x95, 0xf5, 0x4d, 0x6b, 0x78, 0xa7, 0x29, 0xa2, 0xa3, 0xa7, 0x9d, 0x32,
	0xc8, 0x2e, 0x5e, 0xa3, 0x04, 0x29, 0x6e, 0x55, 0xb3, 0x3a, 0x7a, 0x2b, 0x9d, 0xc6, 0x2a, 0x54,
	0x5b, 0x6a, 0x57, 0xd9, 0xcf, 0xf2, 0x1f, 0x4a, 0x53, 0x26, 0x63, 0xb7, 0x8f, 0x97, 0xef, 0xe5,
	0x4b, 0xc0, 0xfb, 0x2c, 0x5e, 0x75, 0x9e, 0x34, 0x9c, 0x95, 0x55, 0x51, 0x17, 0x48, 0x1a, 0x7e,
	0x7e, 0x99, 0x15, 0x45, 0x96, 0xeb, 0xa9, 0x99, 0xac, 0x37, 0x6f, 0xd3, 0x9f, 0x2a, 0x2d, 0x4b,
	0x5d, 0x7d, 0x77, 0x8e, 0xff, 0x4b, 0x60, 0xb8, 0x48, 0xeb, 0x97, 0xf7, 0x65, 0x5d, 0x7d, 0x7c,
	0x65, 0x38, 0x03, 0xbb, 0xde, 0x96, 0x7a, 0x64, 0x8d, 0xad, 0x89, 0xc7, 0xaf, 0x58, 0xc3, 0xd9,
	0xde, 0xf1, 0x3e, 0x47, 0xdb, 0x52, 0x2b, 0x23, 0x23, 0x87, 0x7e, 0x93, 0xe6, 0x1b, 0x3d, 0x22,
	0x63, 0x6b, 0x32, 0xe4, 0x17, 0xac, 0x8b, 0xb2, 0x5d, 0x94, 0x75, 0x1b, 0xab, 0xd6, 0x51, 0x9d,
	0x8a, 0xd7, 0x00, 0x06, 0x12, 0x93, 0xeb, 0x99, 0xdc, 0xd9, 0x61, 0xce, 0x6c, 0x98, 0x90, 0xdb,
	0xec, 0xd0, 0xbf, 0x87, 0xd3, 0x83, 0x67, 0xa0, 0x0b, 0x7d, 0x19, 0x8b, 0xdb, 0x88, 0x1e, 0xb5,
	0xa8, 0xe4, 0x9d, 0x8c, 0xa9, 0x85, 0x1e, 0x40, 0xf8, 0x10, 0x25, 0xf2, 0xe9, 0x59, 0xcc, 0x97,
	0x94, 0xa0, 0x03, 0x24, 0x08, 0x69, 0x0f, 0x01, 0x9c, 0x76, 0x1e, 0x84, 0xd4, 0xf6, 0x39, 0xb8,
	0xff, 0x11, 0x1c, 0x80, 0x1d, 0xc9, 0xb8, 0xbd, 0xe5, 0x04, 0xdc, 0x47, 0xa1, 0xc4, 0x42, 0x46,
	0x52, 0x51, 0x0b, 0x8f, 0x61, 0xb0, 0x12, 0x2a, 0x10, 0x37, 0x73, 0x49, 0xc9, 0xda, 0x31, 0xff,
	0x9a, 0xfd, 0x05, 0x00, 0x00, 0xff, 0xff, 0x46, 0x96, 0xcc, 0xae, 0x70, 0x01, 0x00, 0x00,
}
