// Code generated by protoc-gen-go. DO NOT EDIT.
// source: response.proto

package v2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DiscoverResponse_DiscoverResponseType int32

const (
	DiscoverResponse_UNKNOWN         DiscoverResponse_DiscoverResponseType = 0
	DiscoverResponse_INSTANCE        DiscoverResponse_DiscoverResponseType = 1
	DiscoverResponse_CLUSTER         DiscoverResponse_DiscoverResponseType = 2
	DiscoverResponse_ROUTING         DiscoverResponse_DiscoverResponseType = 3
	DiscoverResponse_RATE_LIMIT      DiscoverResponse_DiscoverResponseType = 4
	DiscoverResponse_CIRCUIT_BREAKER DiscoverResponse_DiscoverResponseType = 5
	DiscoverResponse_SERVICES        DiscoverResponse_DiscoverResponseType = 6
	DiscoverResponse_NAMESPACES      DiscoverResponse_DiscoverResponseType = 12
)

var DiscoverResponse_DiscoverResponseType_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "INSTANCE",
	2:  "CLUSTER",
	3:  "ROUTING",
	4:  "RATE_LIMIT",
	5:  "CIRCUIT_BREAKER",
	6:  "SERVICES",
	12: "NAMESPACES",
}
var DiscoverResponse_DiscoverResponseType_value = map[string]int32{
	"UNKNOWN":         0,
	"INSTANCE":        1,
	"CLUSTER":         2,
	"ROUTING":         3,
	"RATE_LIMIT":      4,
	"CIRCUIT_BREAKER": 5,
	"SERVICES":        6,
	"NAMESPACES":      12,
}

func (x DiscoverResponse_DiscoverResponseType) String() string {
	return proto.EnumName(DiscoverResponse_DiscoverResponseType_name, int32(x))
}
func (DiscoverResponse_DiscoverResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_response_d78d6ab85317dcfd, []int{4, 0}
}

type SimpleResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleResponse) Reset()         { *m = SimpleResponse{} }
func (m *SimpleResponse) String() string { return proto.CompactTextString(m) }
func (*SimpleResponse) ProtoMessage()    {}
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_d78d6ab85317dcfd, []int{0}
}
func (m *SimpleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleResponse.Unmarshal(m, b)
}
func (m *SimpleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleResponse.Marshal(b, m, deterministic)
}
func (dst *SimpleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleResponse.Merge(dst, src)
}
func (m *SimpleResponse) XXX_Size() int {
	return xxx_messageInfo_SimpleResponse.Size(m)
}
func (m *SimpleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleResponse proto.InternalMessageInfo

func (m *SimpleResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SimpleResponse) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type Response struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Data                 *any.Any `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_d78d6ab85317dcfd, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *Response) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type BatchWriteResponse struct {
	Code                 uint32      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string      `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Size                 uint32      `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Responses            []*Response `protobuf:"bytes,4,rep,name=responses,proto3" json:"responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BatchWriteResponse) Reset()         { *m = BatchWriteResponse{} }
func (m *BatchWriteResponse) String() string { return proto.CompactTextString(m) }
func (*BatchWriteResponse) ProtoMessage()    {}
func (*BatchWriteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_d78d6ab85317dcfd, []int{2}
}
func (m *BatchWriteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchWriteResponse.Unmarshal(m, b)
}
func (m *BatchWriteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchWriteResponse.Marshal(b, m, deterministic)
}
func (dst *BatchWriteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchWriteResponse.Merge(dst, src)
}
func (m *BatchWriteResponse) XXX_Size() int {
	return xxx_messageInfo_BatchWriteResponse.Size(m)
}
func (m *BatchWriteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchWriteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchWriteResponse proto.InternalMessageInfo

func (m *BatchWriteResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BatchWriteResponse) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *BatchWriteResponse) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *BatchWriteResponse) GetResponses() []*Response {
	if m != nil {
		return m.Responses
	}
	return nil
}

type BatchQueryResponse struct {
	Code                 uint32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string     `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Amount               uint32     `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Size                 uint32     `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Data                 []*any.Any `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BatchQueryResponse) Reset()         { *m = BatchQueryResponse{} }
func (m *BatchQueryResponse) String() string { return proto.CompactTextString(m) }
func (*BatchQueryResponse) ProtoMessage()    {}
func (*BatchQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_d78d6ab85317dcfd, []int{3}
}
func (m *BatchQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchQueryResponse.Unmarshal(m, b)
}
func (m *BatchQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchQueryResponse.Marshal(b, m, deterministic)
}
func (dst *BatchQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchQueryResponse.Merge(dst, src)
}
func (m *BatchQueryResponse) XXX_Size() int {
	return xxx_messageInfo_BatchQueryResponse.Size(m)
}
func (m *BatchQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchQueryResponse proto.InternalMessageInfo

func (m *BatchQueryResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BatchQueryResponse) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *BatchQueryResponse) GetAmount() uint32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *BatchQueryResponse) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *BatchQueryResponse) GetData() []*any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type DiscoverResponse struct {
	Code                 uint32                                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string                                `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Type                 DiscoverResponse_DiscoverResponseType `protobuf:"varint,3,opt,name=type,proto3,enum=v2.DiscoverResponse_DiscoverResponseType" json:"type,omitempty"`
	Service              *Service                              `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Routing              *Routing                              `protobuf:"bytes,6,opt,name=routing,proto3" json:"routing,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *DiscoverResponse) Reset()         { *m = DiscoverResponse{} }
func (m *DiscoverResponse) String() string { return proto.CompactTextString(m) }
func (*DiscoverResponse) ProtoMessage()    {}
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_d78d6ab85317dcfd, []int{4}
}
func (m *DiscoverResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoverResponse.Unmarshal(m, b)
}
func (m *DiscoverResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoverResponse.Marshal(b, m, deterministic)
}
func (dst *DiscoverResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoverResponse.Merge(dst, src)
}
func (m *DiscoverResponse) XXX_Size() int {
	return xxx_messageInfo_DiscoverResponse.Size(m)
}
func (m *DiscoverResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoverResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoverResponse proto.InternalMessageInfo

func (m *DiscoverResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DiscoverResponse) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *DiscoverResponse) GetType() DiscoverResponse_DiscoverResponseType {
	if m != nil {
		return m.Type
	}
	return DiscoverResponse_UNKNOWN
}

func (m *DiscoverResponse) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *DiscoverResponse) GetRouting() *Routing {
	if m != nil {
		return m.Routing
	}
	return nil
}

func init() {
	proto.RegisterType((*SimpleResponse)(nil), "v2.SimpleResponse")
	proto.RegisterType((*Response)(nil), "v2.Response")
	proto.RegisterType((*BatchWriteResponse)(nil), "v2.BatchWriteResponse")
	proto.RegisterType((*BatchQueryResponse)(nil), "v2.BatchQueryResponse")
	proto.RegisterType((*DiscoverResponse)(nil), "v2.DiscoverResponse")
	proto.RegisterEnum("v2.DiscoverResponse_DiscoverResponseType", DiscoverResponse_DiscoverResponseType_name, DiscoverResponse_DiscoverResponseType_value)
}

func init() { proto.RegisterFile("response.proto", fileDescriptor_response_d78d6ab85317dcfd) }

var fileDescriptor_response_d78d6ab85317dcfd = []byte{
	// 496 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x6f, 0x9b, 0x40,
	0x10, 0x2d, 0xf6, 0xc6, 0x26, 0x8b, 0x4d, 0x56, 0x9b, 0xa8, 0x72, 0x73, 0xb2, 0x90, 0x2a, 0xb9,
	0x3e, 0x10, 0x89, 0x5e, 0x7a, 0xe9, 0x01, 0xe3, 0x75, 0x8a, 0x3f, 0x70, 0x3b, 0xe0, 0xa4, 0x37,
	0xcb, 0x71, 0x36, 0x0e, 0x52, 0x02, 0x2e, 0x60, 0x4b, 0x54, 0xfd, 0x15, 0xfd, 0x01, 0xfd, 0x49,
	0xfd, 0x4d, 0xd5, 0x2e, 0xd0, 0x54, 0x6d, 0x15, 0xc9, 0x17, 0x34, 0xef, 0xbd, 0x99, 0x37, 0x8f,
	0x01, 0xac, 0x27, 0x3c, 0xdd, 0xc6, 0x51, 0xca, 0xcd, 0x6d, 0x12, 0x67, 0x31, 0xad, 0xed, 0xad,
	0xf3, 0x76, 0xc2, 0xbf, 0xec, 0x78, 0x9a, 0x15, 0xd4, 0x79, 0x3b, 0x89, 0x77, 0x59, 0x18, 0x6d,
	0x4a, 0xf8, 0x6a, 0x13, 0xc7, 0x9b, 0x07, 0x7e, 0x21, 0xd1, 0xcd, 0xee, 0xee, 0x62, 0x15, 0xe5,
	0x85, 0x64, 0xbc, 0xc3, 0xba, 0x1f, 0x3e, 0x6e, 0x1f, 0x38, 0x94, 0xa6, 0x94, 0x62, 0xb4, 0x8e,
	0x6f, 0x79, 0x47, 0xe9, 0x2a, 0xbd, 0x36, 0xc8, 0x5a, 0x70, 0x61, 0x74, 0x17, 0x77, 0x6a, 0x5d,
	0xa5, 0x77, 0x0c, 0xb2, 0x36, 0xee, 0xb1, 0x7a, 0xe8, 0x0c, 0xed, 0x61, 0x74, 0xbb, 0xca, 0x56,
	0x9d, 0x7a, 0x57, 0xe9, 0x69, 0xd6, 0x99, 0x59, 0xe4, 0x32, 0xab, 0x5c, 0xa6, 0x1d, 0xe5, 0x20,
	0x3b, 0xc6, 0x48, 0x6d, 0x91, 0x93, 0x31, 0x52, 0x09, 0x39, 0x35, 0xbe, 0x61, 0x3a, 0x58, 0x65,
	0xeb, 0xfb, 0xeb, 0x24, 0xcc, 0x0e, 0xce, 0x29, 0xb8, 0x34, 0xfc, 0xca, 0xe5, 0xce, 0x36, 0xc8,
	0x9a, 0xf6, 0xf1, 0x71, 0x75, 0xc4, 0xb4, 0x83, 0xba, 0xf5, 0x9e, 0x66, 0xb5, 0xcc, 0xbd, 0x65,
	0x56, 0xe6, 0xf0, 0x24, 0x1b, 0xdf, 0x95, 0x72, 0xfd, 0xa7, 0x1d, 0x4f, 0xf2, 0x83, 0xd7, 0xbf,
	0xc4, 0x8d, 0xd5, 0x63, 0xbc, 0x8b, 0xb2, 0x32, 0x40, 0x89, 0x7e, 0xc7, 0x42, 0x7f, 0xc4, 0xaa,
	0xce, 0x73, 0x24, 0x13, 0x3d, 0x73, 0x1e, 0xe3, 0x47, 0x1d, 0x93, 0x61, 0x98, 0xae, 0xe3, 0x3d,
	0x4f, 0x0e, 0x8e, 0xf4, 0x1e, 0xa3, 0x2c, 0xdf, 0x16, 0x17, 0xd1, 0xad, 0x37, 0xe2, 0xc5, 0xff,
	0xf6, 0xfa, 0x87, 0x08, 0xf2, 0x2d, 0x07, 0x39, 0x46, 0x5f, 0xe3, 0x66, 0xca, 0x93, 0x7d, 0xb8,
	0x2e, 0xc2, 0x6b, 0x96, 0x26, 0x1c, 0xfc, 0x82, 0x82, 0x4a, 0x13, 0x6d, 0xe5, 0x5f, 0xd8, 0x69,
	0x3c, 0xb5, 0x41, 0x41, 0x41, 0xa5, 0x19, 0x3f, 0x15, 0x7c, 0xf6, 0xbf, 0x65, 0x54, 0xc3, 0xcd,
	0x85, 0x37, 0xf1, 0xe6, 0xd7, 0x1e, 0x79, 0x41, 0x5b, 0x58, 0x75, 0x3d, 0x3f, 0xb0, 0x3d, 0x87,
	0x11, 0x45, 0x48, 0xce, 0x74, 0xe1, 0x07, 0x0c, 0x48, 0x4d, 0x00, 0x98, 0x2f, 0x02, 0xd7, 0xbb,
	0x24, 0x75, 0xaa, 0x63, 0x0c, 0x76, 0xc0, 0x96, 0x53, 0x77, 0xe6, 0x06, 0x04, 0xd1, 0x53, 0x7c,
	0xe2, 0xb8, 0xe0, 0x2c, 0xdc, 0x60, 0x39, 0x00, 0x66, 0x4f, 0x18, 0x90, 0x23, 0x61, 0xe6, 0x33,
	0xb8, 0x72, 0x1d, 0xe6, 0x93, 0x86, 0x18, 0xf1, 0xec, 0x19, 0xf3, 0x3f, 0xda, 0x02, 0xb7, 0x0c,
	0xa4, 0x36, 0x89, 0xd6, 0x47, 0x33, 0xe6, 0x7f, 0xe8, 0x6b, 0xe2, 0xb9, 0x74, 0xe6, 0xde, 0xc8,
	0xbd, 0xec, 0xeb, 0xa3, 0xe9, 0xe2, 0xf3, 0x72, 0x38, 0x00, 0x36, 0x02, 0x21, 0xaa, 0x12, 0xfb,
	0xc3, 0x49, 0x5f, 0x2b, 0x2a, 0x06, 0x57, 0x0c, 0xc6, 0x48, 0xd5, 0x88, 0x7e, 0xd3, 0x90, 0x1f,
	0xed, 0xed, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x03, 0x7f, 0xd8, 0x7f, 0xad, 0x03, 0x00, 0x00,
}
