name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

# Always force the use of Go modules
env:
  GO111MODULE: on

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      # Setup the environment.
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      # Checkout latest code
      - name: Checkout repo
        uses: actions/checkout@v2

      # Execute vert check
      - name: Vert check
        run: bash vert.sh -install && bash vert.sh

      # Compile
      - name: Build server
        run: bash build.sh
        
      # Run unit tests
      - name: run tests
        run: |
          pushd ./naming/cache
          go test -v
          popd
          pushd ./plugin/ratelimit/tokenBucket
          go test -v
          popd
          pushd ./store/defaultStore
          go test -v
          popd
          
      # Run interface tests
#      - name: run interface tests
#        run: |
#          work_dir=$(ls | grep polaris-server-release | sed -n '1p')
#          echo "work_dir is $work_dir"
#          cd $work_dir
#         ls -al
#          chmod +x ./tool/*.sh
#          ./tool/install.sh
#          cd ..
#          pushd ./test
#          go test -count=1 -v
#          popd
#          cd $work_dir
#          ./tool/uninstall.sh
#          cd ..